// test/outils/balayage_correspondance_test.dart
//
// Le BALAYAGE de la correspondance IA → FCÉN (palier 4) : 274 ingrédients
// et plats d'ici et d'ailleurs, nommés comme l'IA les nomme (nom, quantité,
// unité, kcal estimées, mots-clés, taille, grammes), passés dans
// `correspondre` avec la vraie base. Chaque ligne dit l'aliment choisi ;
// « ✗ » hors de la base, « ⚠ » des calories loin de l'estimation. À relire
// À L'ŒIL après toute retouche de `correspondance.dart` (comparer avant /
// après) — une confusion (vin → vinaigre) ne se voit qu'ici :
//   flutter test --dart-define=BALAYAGE=true test/outils/balayage_correspondance_test.dart

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:rhythm/modele/alimentation/base_aliments.dart';
import 'package:rhythm/modele/alimentation/correspondance.dart';

const _balayage = bool.fromEnvironment('BALAYAGE');

typedef _C = (String, num, String, num?, String, String?, num?);

const List<_C> _cas = [
  ("Carottes", 2, "unite", 50, "carotte crue", "moyen", 120),
  ("Pommes de terre", 4, "unite", 620, "pomme de terre crue", "moyen", 800),
  ("Patate douce", 1, "unite", 170, "patate douce crue", "moyen", 200),
  ("Brocoli", 300, "g", 100, "brocoli cru", null, null),
  ("Chou-fleur", 1, "unite", 150, "chou-fleur cru", "moyen", 600),
  ("Poivron rouge", 1, "unite", 35, "poivron rouge cru", "moyen", 120),
  ("Poivron vert", 1, "unite", 25, "poivron vert cru", "moyen", 120),
  ("Courgettes", 2, "unite", 70, "courgette crue", "moyen", 400),
  ("Aubergine", 1, "unite", 110, "aubergine crue", "moyen", 450),
  ("Champignons blancs", 227, "g", 50, "champignons blancs crus", null, null),
  ("Épinards", 142, "g", 33, "épinards crus", null, null),
  ("Laitue romaine", 200, "g", 34, "laitue romaine crue", null, null),
  ("Concombre", 1, "unite", 45, "concombre cru", "moyen", 300),
  ("Tomates", 3, "unite", 66, "tomate crue", "moyen", 370),
  ("Tomates cerises", 250, "g", 45, "tomates cerises crues", null, null),
  ("Ail", 3, "unite", 13, "ail cru", "gousse", 9),
  ("Gingembre frais", 15, "g", 12, "gingembre racine crue", null, null),
  ("Oignon rouge", 1, "unite", 60, "oignon rouge cru", "moyen", 150),
  ("Échalotes françaises", 2, "unite", 36, "échalote crue", "moyen", 50),
  ("Oignons verts", 4, "unite", 20, "oignon vert cru", null, 60),
  ("Céleri", 2, "unite", 12, "céleri cru", "branche", 80),
  ("Maïs en grains surgelé", 250, "ml", 120, "maïs sucré congelé", null, 140),
  ("Petits pois surgelés", 250, "ml", 110, "pois verts congelés", null, 140),
  ("Haricots verts", 250, "g", 78, "haricots verts crus", null, null),
  ("Chou vert", 500, "g", 125, "chou vert cru", null, null),
  ("Chou rouge", 300, "g", 93, "chou rouge cru", null, null),
  ("Betteraves", 3, "unite", 108, "betterave crue", "moyen", 250),
  ("Navet", 1, "unite", 84, "navet cru", "moyen", 300),
  ("Poireau", 1, "unite", 55, "poireau cru", "moyen", 90),
  ("Avocat", 1, "unite", 240, "avocat cru", "moyen", 150),
  ("Jus de citron", 30, "ml", 7, "jus de citron", null, null),
  ("Jus de lime", 15, "ml", 4, "jus de lime", null, null),
  ("Coriandre fraîche", 15, "g", 3, "coriandre fraîche", null, null),
  ("Persil frais", 15, "g", 5, "persil frais", null, null),
  ("Chou frisé (kale)", 200, "g", 70, "chou frisé cru", null, null),
  ("Pois mange-tout", 200, "g", 84, "pois mange-tout crus", null, null),
  ("Asperges", 250, "g", 50, "asperges crues", null, null),
  ("Courge spaghetti", 1, "unite", 310, "courge spaghetti crue", "moyen", 1000),
  ("Bananes plantains", 2, "unite", 440, "banane plantain crue", "moyen", 360),
  ("Manioc", 500, "g", 800, "manioc cru", null, null),
  ("Gombos", 200, "g", 66, "gombo cru", null, null),
  ("Igname", 400, "g", 470, "igname crue", null, null),
  ("Bananes", 2, "unite", 210, "banane crue", "moyen", 236),
  ("Pomme", 1, "unite", 95, "pomme crue avec pelure", "moyen", 180),
  ("Bleuets", 250, "ml", 84, "bleuets crus", null, 148),
  ("Bleuets surgelés", 250, "ml", 80, "bleuets congelés", null, 150),
  ("Fraises", 250, "g", 80, "fraises crues", null, null),
  ("Framboises", 125, "ml", 32, "framboises crues", null, 62),
  ("Orange", 1, "unite", 62, "orange crue", "moyen", 130),
  ("Mangue", 1, "unite", 120, "mangue crue", "moyen", 200),
  ("Ananas", 250, "g", 125, "ananas cru", null, null),
  ("Raisins secs", 60, "ml", 130, "raisins secs", null, 40),
  (
    "Canneberges séchées",
    60,
    "ml",
    120,
    "canneberges séchées sucrées",
    null,
    35,
  ),
  ("Dattes", 4, "unite", 88, "dattes", "moyen", 32),
  ("Noix de coco râpée", 30, "g", 200, "noix de coco râpée séchée", null, null),
  ("Bœuf haché maigre", 450, "g", 900, "boeuf haché maigre cru", null, null),
  (
    "Bœuf haché mi-maigre",
    450,
    "g",
    1100,
    "boeuf haché mi-maigre cru",
    null,
    null,
  ),
  ("Porc haché", 450, "g", 1180, "porc haché cru", null, null),
  ("Longe de porc", 600, "g", 860, "porc longe crue", null, null),
  ("Côtelettes de porc", 4, "unite", 840, "porc côtelette crue", null, 600),
  (
    "Hauts de cuisse de poulet désossés",
    600,
    "g",
    720,
    "poulet cuisse sans peau crue",
    null,
    null,
  ),
  ("Pilons de poulet", 8, "unite", 1200, "poulet pilon cru", null, 900),
  ("Poulet entier", 1, "unite", 2000, "poulet entier cru", null, 1500),
  ("Poulet cuit effiloché", 200, "g", 330, "poulet rôti viande", null, null),
  ("Bacon", 4, "unite", 320, "bacon cru", "tranche", 80),
  ("Jambon cuit tranché", 100, "g", 110, "jambon tranché", null, null),
  (
    "Saucisses italiennes",
    4,
    "unite",
    1200,
    "saucisse italienne porc crue",
    null,
    400,
  ),
  ("Agneau haché", 450, "g", 1270, "agneau haché cru", null, null),
  ("Steak de surlonge", 400, "g", 640, "boeuf surlonge crue", null, null),
  ("Cubes de bœuf à ragoût", 700, "g", 1000, "boeuf ragoût cru", null, null),
  ("Viande de chèvre", 500, "g", 550, "chèvre viande crue", null, null),
  ("Foies de poulet", 300, "g", 350, "foie poulet cru", null, null),
  ("Filets de saumon", 500, "g", 1000, "saumon atlantique cru", null, null),
  ("Thon en conserve", 120, "g", 140, "thon pâle conserve eau", null, null),
  ("Crevettes", 400, "g", 340, "crevettes crues", null, null),
  ("Morue", 500, "g", 410, "morue crue", null, null),
  ("Morue salée", 300, "g", 870, "morue salée séchée", null, null),
  (
    "Sardines en conserve",
    100,
    "g",
    208,
    "sardines conserve huile",
    null,
    null,
  ),
  ("Tofu ferme", 350, "g", 500, "tofu ferme", null, null),
  ("Oeufs", 4, "unite", 286, "oeuf entier cru", "gros", 200),
  ("Lait 2 %", 250, "ml", 130, "lait 2 %", null, null),
  ("Lait écrémé", 250, "ml", 90, "lait écrémé", null, null),
  ("Crème 35 %", 125, "ml", 420, "crème 35 %", null, null),
  ("Crème 15 % à cuisson", 250, "ml", 420, "crème 15 %", null, null),
  ("Crème sure", 125, "ml", 240, "crème sure", null, null),
  ("Beurre", 30, "g", 215, "beurre", null, null),
  ("Cheddar râpé", 250, "ml", 400, "fromage cheddar", null, 100),
  ("Mozzarella", 200, "g", 600, "fromage mozzarella", null, null),
  ("Parmesan râpé", 30, "g", 120, "fromage parmesan râpé", null, null),
  ("Fromage à la crème", 125, "g", 440, "fromage à la crème", null, null),
  ("Ricotta", 250, "g", 430, "fromage ricotta", null, null),
  ("Yogourt grec 0 %", 175, "g", 100, "yogourt grec 0%", null, null),
  ("Lait de coco", 400, "ml", 800, "lait de coco conserve", null, null),
  (
    "Boisson d'amande non sucrée",
    250,
    "ml",
    40,
    "boisson amande non sucrée",
    null,
    null,
  ),
  ("Boisson de soya", 250, "ml", 100, "boisson soya", null, null),
  ("Flocons d'avoine", 250, "ml", 300, "avoine flocons secs", null, 80),
  ("Farine tout usage", 500, "ml", 950, "farine blé tout usage", null, 260),
  ("Farine de blé entier", 250, "ml", 400, "farine blé entier", null, 120),
  ("Quinoa", 250, "ml", 630, "quinoa sec", null, 170),
  ("Couscous", 250, "ml", 650, "couscous sec", null, 180),
  ("Orge perlé", 125, "ml", 350, "orge perlé sec", null, 100),
  ("Riz brun", 250, "ml", 680, "riz brun cru", null, 190),
  ("Pain de blé entier", 2, "unite", 170, "pain blé entier", "tranche", 70),
  ("Tortillas de blé", 4, "unite", 600, "tortilla farine blé", "moyen", 200),
  ("Pains pitas", 2, "unite", 330, "pain pita", "moyen", 120),
  ("Chapelure", 125, "ml", 230, "chapelure", null, 60),
  ("Nouilles de riz", 250, "g", 900, "nouilles riz sèches", null, null),
  ("Nouilles aux oeufs", 250, "g", 950, "nouilles oeufs sèches", null, null),
  ("Macaronis", 250, "g", 930, "macaroni sec", null, null),
  ("Fécule de maïs", 15, "ml", 30, "fécule de maïs", null, 8),
  ("Semoule de maïs", 250, "ml", 440, "semoule de maïs", null, 120),
  (
    "Pois chiches en conserve",
    540,
    "ml",
    480,
    "pois chiches conserve",
    null,
    400,
  ),
  ("Lentilles vertes", 250, "ml", 700, "lentilles sèches", null, 200),
  (
    "Haricots rouges en conserve",
    540,
    "ml",
    420,
    "haricots rouges conserve",
    null,
    400,
  ),
  (
    "Haricots blancs en conserve",
    540,
    "ml",
    420,
    "haricots blancs conserve",
    null,
    400,
  ),
  ("Haricots noirs secs", 250, "ml", 680, "haricots noirs secs", null, 200),
  ("Edamames", 250, "ml", 190, "edamame congelés", null, 155),
  (
    "Tomates en dés en conserve",
    796,
    "ml",
    150,
    "tomates dés conserve",
    null,
    800,
  ),
  ("Sauce tomate", 213, "ml", 60, "sauce tomate conserve", null, 215),
  ("Maïs en crème", 398, "ml", 300, "maïs crème conserve", null, 400),
  (
    "Bouillon de légumes",
    1000,
    "ml",
    60,
    "bouillon légumes prêt à servir",
    null,
    1000,
  ),
  (
    "Bouillon de bœuf",
    500,
    "ml",
    30,
    "bouillon boeuf prêt à servir",
    null,
    500,
  ),
  ("Sauce soya", 30, "ml", 20, "sauce soya", null, 32),
  ("Ketchup", 30, "ml", 40, "ketchup", null, 34),
  ("Moutarde de Dijon", 15, "ml", 15, "moutarde dijon", null, 15),
  ("Mayonnaise", 30, "ml", 200, "mayonnaise", null, 28),
  ("Sauce Worcestershire", 15, "ml", 12, "sauce worcestershire", null, 16),
  ("Sriracha", 10, "ml", 10, "sauce piquante", null, 10),
  ("Sirop d'érable", 60, "ml", 210, "sirop érable", null, 80),
  ("Miel", 30, "ml", 128, "miel", null, 42),
  ("Vinaigre de cidre", 15, "ml", 3, "vinaigre cidre", null, 15),
  ("Vinaigre balsamique", 15, "ml", 14, "vinaigre balsamique", null, 16),
  ("Salsa", 125, "ml", 40, "salsa", null, 130),
  ("Pesto", 60, "ml", 300, "pesto basilic", null, 60),
  ("Beurre d'arachide", 30, "ml", 190, "beurre d'arachide", null, 32),
  ("Tahini", 30, "ml", 180, "tahini sésame", null, 30),
  ("Sauce hoisin", 30, "ml", 70, "sauce hoisin", null, 32),
  ("Sauce de poisson", 15, "ml", 6, "sauce poisson", null, 18),
  ("Sucre", 125, "ml", 400, "sucre blanc granulé", null, 100),
  ("Cassonade", 60, "ml", 200, "cassonade", null, 50),
  ("Chocolat noir", 50, "g", 300, "chocolat noir 70%", null, null),
  (
    "Pépites de chocolat",
    125,
    "ml",
    400,
    "pépites chocolat mi-sucré",
    null,
    85,
  ),
  ("Poudre à pâte", 5, "ml", 3, "poudre à pâte", null, 5),
  ("Levure sèche", 8, "g", 25, "levure sèche active", null, null),
  ("Extrait de vanille", 5, "ml", 12, "vanille extrait", null, 4),
  ("Cacao en poudre", 30, "ml", 25, "cacao poudre non sucré", null, 5),
  ("Huile de canola", 30, "ml", 250, "huile canola", null, 28),
  ("Huile d'olive", 30, "ml", 240, "huile olive", null, 27),
  ("Huile de sésame", 15, "ml", 120, "huile sésame", null, 14),
  ("Huile de coco", 15, "ml", 120, "huile coco", null, 14),
  ("Cumin moulu", 5, "ml", 8, "cumin moulu", null, 2),
  ("Paprika fumé", 5, "ml", 6, "paprika", null, 2),
  ("Cannelle", 5, "ml", 6, "cannelle moulue", null, 2),
  ("Origan séché", 5, "ml", 3, "origan séché", null, 1),
  ("Curcuma", 5, "ml", 8, "curcuma moulu", null, 3),
  ("Graines de sésame", 15, "ml", 50, "graines sésame", null, 9),
  ("Graines de chia", 30, "ml", 130, "graines chia", null, 24),
  ("Graines de lin moulues", 30, "ml", 75, "graines lin moulues", null, 14),
  ("Amandes", 60, "ml", 200, "amandes", null, 35),
  ("Noix de Grenoble", 60, "ml", 200, "noix grenoble", null, 30),
  ("Arachides", 60, "ml", 210, "arachides rôties", null, 36),
  ("Noix de cajou", 60, "ml", 200, "noix cajou", null, 35),
  ("Café", 250, "ml", 2, "café infusé", null, 250),
  ("Thé", 250, "ml", 2, "thé infusé", null, 250),
  ("Jus d'orange", 250, "ml", 110, "jus orange", null, 260),
  ("Bière", 355, "ml", 150, "bière", null, 360),
  ("Vin rouge", 150, "ml", 125, "vin rouge", null, 150),
  ("Lait au chocolat", 250, "ml", 200, "lait chocolat", null, 260),
  ("Hamburger", 1, "unite", 550, "hamburger restaurant", null, 250),
  ("Frites", 150, "g", 450, "frites restaurant", null, null),
  ("Shawarma au poulet", 1, "unite", 700, "shawarma poulet", null, 350),
  ("Sushis", 240, "g", 380, "sushi poisson", null, null),
  ("Pad thaï", 400, "g", 520, "pad thaï poulet", null, null),
  (
    "Spaghetti sauce à la viande",
    450,
    "g",
    700,
    "spaghetti sauce viande",
    null,
    null,
  ),
  ("Chow mein au poulet", 400, "g", 340, "chow mein poulet", null, null),
  ("Muffin aux bleuets", 1, "unite", 400, "muffin bleuets", null, 110),
  ("Beigne", 1, "unite", 250, "beigne", null, 60),
  ("Croissant", 1, "unite", 240, "croissant", null, 60),
  ("Bagel", 1, "unite", 270, "bagel nature", null, 100),
  ("Hot-dog", 1, "unite", 290, "hot dog", null, 100),
  ("Salade César", 200, "g", 350, "salade césar", null, null),
  ("Lasagne à la viande", 350, "g", 550, "lasagne viande", null, null),
  ("Pois congo", 540, "ml", 400, "pois cajan conserve", null, 400),
  ("Hareng saur", 150, "g", 330, "hareng fumé", null, null),
  ("Épis de maïs", 2, "unite", 180, "maïs sucré épi cru", "moyen", 200),
  ("Piment scotch bonnet", 1, "unite", 5, "piment fort cru", "petit", 10),
  ("Thym frais", 5, "g", 5, "thym frais", null, null),
  ("Clous de girofle", 2, "unite", 1, "girofle", null, 1),
  ("Arachides crues", 125, "ml", 400, "arachides crues", null, 70),
  ("Farine de manioc (gari)", 250, "ml", 500, "manioc farine", null, 140),
  ("Feuilles de manioc", 300, "g", 110, "feuilles de manioc", null, null),
  ("Huile de palme", 30, "ml", 250, "huile palme", null, 27),
  ("Sauce d'huître", 30, "ml", 30, "sauce huître", null, 32),
  ("Bok choy", 300, "g", 40, "chou chinois pak choi cru", null, null),
  (
    "Champignons shiitake",
    150,
    "g",
    50,
    "champignons shiitake crus",
    null,
    null,
  ),
  ("Citronnelle", 1, "unite", 5, "citronnelle crue", "tige", 20),
  ("Feuilles de nori", 2, "unite", 10, "algue nori séchée", "feuille", 6),
  ("Miso", 30, "ml", 60, "miso", null, 35),
  ("Kimchi", 125, "ml", 20, "kimchi", null, 100),
  ("Nouilles soba", 250, "g", 840, "nouilles soba sèches", null, null),
  ("Vermicelles de riz", 200, "g", 720, "vermicelles riz secs", null, null),
  ("Germes de soya", 200, "g", 60, "germes de haricots mungo crus", null, null),
  ("Jalapeño", 1, "unite", 4, "piment jalapeño cru", "moyen", 14),
  ("Haricots frits", 398, "ml", 380, "haricots frits conserve", null, 400),
  ("Tortillas de maïs", 6, "unite", 330, "tortilla maïs", "moyen", 150),
  ("Olives noires", 60, "ml", 50, "olives noires conserve", null, 35),
  ("Câpres", 15, "ml", 3, "câpres conserve", null, 9),
  ("Tomates séchées", 60, "ml", 70, "tomates séchées", null, 27),
  ("Cœurs d'artichauts", 398, "ml", 90, "artichauts conserve", null, 240),
  ("Roquette", 100, "g", 25, "roquette crue", null, null),
  ("Mascarpone", 125, "g", 540, "fromage mascarpone", null, null),
  ("Polenta", 250, "ml", 600, "semoule de maïs polenta sèche", null, 160),
  ("Gnocchis", 500, "g", 800, "gnocchis pommes de terre", null, null),
  ("Prosciutto", 60, "g", 150, "jambon prosciutto", null, null),
  ("Pancetta", 100, "g", 460, "pancetta crue", null, null),
  ("Levure alimentaire", 15, "g", 50, "levure alimentaire", null, null),
  ("Beurre non salé", 30, "g", 215, "beurre non salé", null, null),
  ("Huile végétale", 30, "ml", 250, "huile végétale", null, 27),
  ("Margarine", 30, "g", 210, "margarine", null, null),
  ("Crème de coco", 160, "ml", 480, "crème de coco conserve", null, 160),
  (
    "Lait concentré sucré",
    300,
    "ml",
    1000,
    "lait concentré sucré conserve",
    null,
    380,
  ),
  ("Lait évaporé", 370, "ml", 500, "lait évaporé conserve", null, 380),
  ("Sucre à glacer", 250, "ml", 480, "sucre à glacer", null, 125),
  ("Mélasse", 30, "ml", 120, "mélasse", null, 40),
  ("Gélatine", 7, "g", 25, "gélatine sèche", null, null),
  ("Pâte feuilletée", 200, "g", 1100, "pâte feuilletée congelée", null, null),
  ("Pain naan", 1, "unite", 260, "pain naan", null, 90),
  ("Baguette", 100, "g", 270, "pain baguette", null, null),
  ("Pains à hamburger", 4, "unite", 480, "pain hamburger", null, 200),
  ("Fromage suisse", 50, "g", 190, "fromage suisse", null, null),
  ("Feta", 100, "g", 265, "fromage feta", null, null),
  ("Fromage de chèvre", 100, "g", 300, "fromage de chèvre mou", null, null),
  ("Fromage cottage", 250, "ml", 220, "fromage cottage 2%", null, 225),
  (
    "Blancs d'oeufs liquides",
    250,
    "ml",
    125,
    "blancs oeufs liquides",
    null,
    250,
  ),
  ("Saumon fumé", 100, "g", 120, "saumon fumé", null, null),
  ("Pétoncles", 400, "g", 280, "pétoncles crus", null, null),
  ("Moules", 1000, "g", 860, "moules crues", null, null),
  ("Aiglefin", 450, "g", 330, "aiglefin cru", null, null),
  ("Crabe", 200, "g", 170, "crabe cuit", null, null),
  ("Canard", 400, "g", 540, "canard viande crue", null, null),
  ("Veau haché", 450, "g", 650, "veau haché cru", null, null),
  (
    "Bœuf haché extra-maigre",
    450,
    "g",
    700,
    "boeuf haché extra maigre cru",
    null,
    null,
  ),
  ("Rôti de palette", 1200, "g", 2400, "boeuf palette cru", null, null),
  ("Chorizo", 150, "g", 680, "chorizo", null, null),
  ("Pepperoni", 50, "g", 250, "pepperoni", null, null),
  ("Salami", 50, "g", 200, "salami", null, null),
  (
    "Poitrine de dinde tranchée",
    100,
    "g",
    105,
    "dinde poitrine tranchée charcuterie",
    null,
    null,
  ),
  ("Pois verts secs cassés", 250, "ml", 700, "pois cassés secs", null, 200),
  ("Riz sauvage", 125, "ml", 290, "riz sauvage cru", null, 80),
  ("Boulgour", 250, "ml", 480, "boulgour sec", null, 140),
  ("Farine d'avoine", 250, "ml", 400, "farine avoine", null, 100),
  ("Son de blé", 60, "ml", 30, "son de blé", null, 15),
  ("Granola", 125, "ml", 280, "granola", null, 60),
  ("Craquelins", 30, "g", 130, "craquelins blé", null, null),
  ("Croustilles", 50, "g", 270, "croustilles pommes de terre", null, null),
  ("Maïs soufflé", 750, "ml", 90, "maïs soufflé à air", null, 24),
  ("Barre tendre", 1, "unite", 130, "barre granola", null, 30),
  ("Crème glacée vanille", 125, "ml", 140, "crème glacée vanille", null, 66),
  ("Yogourt aux fraises", 175, "g", 170, "yogourt fraises", null, null),
  ("Compote de pommes", 125, "ml", 60, "compote pommes non sucrée", null, 125),
  ("Confiture de fraises", 15, "ml", 50, "confiture fraises", null, 20),
  (
    "Tartinade chocolat noisettes",
    15,
    "ml",
    100,
    "tartinade chocolat noisettes",
    null,
    19,
  ),
  ("Hummus", 60, "ml", 100, "hoummos", null, 60),
  ("Guacamole", 60, "ml", 90, "guacamole", null, 60),
  ("Tzatziki", 60, "ml", 50, "tzatziki", null, 60),
  ("Sauce BBQ", 30, "ml", 50, "sauce barbecue", null, 34),
  ("Vinaigrette italienne", 30, "ml", 90, "vinaigrette italienne", null, 30),
  ("Jus de pomme", 250, "ml", 115, "jus pomme", null, 260),
  ("Boisson gazeuse", 355, "ml", 150, "boisson gazeuse cola", null, 370),
  ("Eau pétillante", 355, "ml", 0, "eau gazéifiée", null, 355),
  ("Kombucha", 250, "ml", 30, "kombucha", null, 250),
  ("Thé glacé", 250, "ml", 90, "thé glacé sucré", null, 250),
  ("Smoothie aux fruits", 300, "ml", 180, "smoothie fruits", null, 300),
  (
    "Protéine en poudre",
    30,
    "g",
    120,
    "poudre protéines lactosérum",
    null,
    null,
  ),
  // Vus sur le vrai Groq (25 sept., suite 9).
  ("Huile d'olive", 15, "ml", 40, "huile d'olive", null, 14),
  ("Boeuf à braiser, cubes", 400, "g", 800, "boeuf à braiser cru", null, null),
  ("Concentré de tomate", 30, "ml", 30, "concentré de tomate", null, 33),
  (
    "Bouillon poisson prêt à servir",
    500,
    "ml",
    20,
    "bouillon poisson prêt à servir",
    null,
    500,
  ),
  ("Pepsi", 355, "ml", 150, "boisson cola", null, 370),
  ("Dressing César", 30, "ml", 120, "dressing César", null, 30),
  ("Tofu ferme émietté", 400, "g", 320, "tofu ferme", null, null),
  ("Chou blanc", 300, "g", 75, "chou blanc cru", null, null),
  ("Poulet", 800, "g", 1320, "poulet morceaux cru", null, null),
];

void main() {
  test('balayage', skip: !_balayage, () {
    final base = BaseAliments.analyser(
      File('assets/donnees/fcen.txt').readAsStringSync(),
    );
    var hors = 0, ecarts = 0;
    for (final (nom, q, u, kcal, fcen, taille, g) in _cas) {
      final p = IngredientPropose.depuisJson({
        'nom': nom,
        'quantite': q,
        'unite': u,
        'kcal': ?kcal,
        'fcen': fcen,
        'taille': ?taille,
        'grammes': g ?? (u == 'unite' ? null : q),
      })!;
      final c = correspondre(p, base);
      final x = c.ingredient;
      final k = c.nutriments.kcal;
      final ratio = kcal == null || kcal == 0 ? 1 : k / kcal;
      final marque = c.horsBase
          ? '✗'
          : (ratio > 2 || ratio < 0.5)
          ? '⚠'
          : ' ';
      if (c.horsBase) hors++;
      if (marque == '⚠') ecarts++;
      // ignore: avoid_print
      print(
        '$marque $nom → ${c.aliment?.nom ?? (p.libre ? 'libre' : 'HORS BASE')}'
        '${x.mesure == null ? '' : ' [${x.nombre} × ${x.mesure}]'}'
        ' ${x.grammes?.round()} g = ${k.round()} (IA $kcal)',
      );
    }
    // ignore: avoid_print
    print('${_cas.length} cas, $hors hors base, $ecarts écarts');
  });
}
