// lib/modele/sports/catalogue/cardio.dart
//
// La banque : HIIT, CIRCUIT ET CARDIO — sauts, burpees, grimpeurs, corde,
// boxe ; course, marche, vélo.

import 'raccourcis.dart';

const List<ExerciceSport> exercicesCardio = [
  // ── HIIT et circuit ──────────────────────────────────────────────────────
  ExerciceSport(
    'jumping_jack',
    'Jumping jacks',
    hiit,
    'jumping_jack',
    principaux: [mol, epa],
    secondaires: [qua, add],
    mesure: duree,
    etapes: [
      'Debout, pieds joints, bras le long du corps.',
      'Saute en écartant les jambes, les bras montent au-dessus de la tête.',
      'Reviens pieds joints, bras en bas, et enchaîne.',
    ],
    erreurs: ['Atterrir talons en premier.', 'Bras à moitié.'],
    respiration: rHiit,
  ),
  ExerciceSport(
    'jacks_sans_saut',
    'Jacks sans saut',
    hiit,
    'jacks_sans_saut',
    principaux: [epa, mol],
    mesure: duree,
    etapes: [
      'Écarte une jambe sur le côté en levant les bras.',
      "Reviens, puis l'autre jambe.",
      'Garde un rythme vif, sans impact.',
    ],
    erreurs: ['Ralentir.', 'Bras paresseux.'],
    respiration: rHiit,
    met: 5,
  ),
  ExerciceSport(
    'star_jump',
    'Sauts en étoile',
    hiit,
    'star_jump',
    principaux: [qua, mol],
    secondaires: [fes, epa],
    niveau: inter,
    etapes: [
      'Accroupis-toi légèrement.',
      'Saute en écartant bras et jambes en étoile.',
      'Atterris souplement, pieds rapprochés, et recommence.',
    ],
    erreurs: ['Atterrir jambes tendues.', 'Dos rond au départ.'],
    respiration: rHiit,
    intensite: 2,
  ),
  ExerciceSport(
    'burpee_sans_saut',
    'Burpees sans saut',
    hiit,
    'burpee_sans_saut',
    principaux: [qua, pec],
    secondaires: [abd, epa],
    poly: true,
    etapes: [
      'Accroupis-toi, mains au sol.',
      "Recule un pied puis l'autre en planche.",
      'Ramène les pieds un à un et relève-toi.',
    ],
    erreurs: ["Dos qui s'affaisse en planche.", 'Pieds trop loin.'],
    respiration: rHiit,
    met: 6,
  ),
  ExerciceSport(
    'burpee',
    'Burpees',
    hiit,
    'burpee',
    principaux: [qua, pec],
    secondaires: [abd, epa, fes],
    poly: true,
    niveau: inter,
    etapes: [
      'Accroupis-toi, mains au sol.',
      'Saute les pieds en arrière en planche.',
      "Ramène-les d'un saut, puis saute bras en l'air.",
    ],
    erreurs: ['Bassin qui tombe en planche.', 'Atterrir raide.'],
    respiration: rHiit,
    intensite: 2,
    met: 10,
  ),
  ExerciceSport(
    'burpee_pompe',
    'Burpees avec pompe',
    hiit,
    'burpee_pompe',
    principaux: [qua, pec, tri],
    secondaires: [abd, epa],
    poly: true,
    niveau: av,
    etapes: [
      'Comme un burpee, avec une vraie pompe en planche.',
      'Poitrine au sol, repousse, ramène les pieds.',
      "Saute bras en l'air.",
    ],
    erreurs: ['Pompe bâclée.', 'Dos cambré.'],
    respiration: rHiit,
    intensite: 3,
    met: 10,
  ),
  ExerciceSport(
    'mountain_climber',
    'Grimpeurs',
    hiit,
    'mountain_climber',
    principaux: [abd],
    secondaires: [qua, epa],
    mesure: duree,
    etapes: [
      'En planche haute, mains sous les épaules.',
      "Ramène un genou vers la poitrine, puis l'autre, vite.",
      'Garde le bassin bas et stable.',
    ],
    erreurs: ['Fesses trop hautes.', 'Épaules qui reculent.'],
    respiration: rHiit,
    met: 8,
  ),
  ExerciceSport(
    'montees_genoux',
    'Montées de genoux',
    hiit,
    'montees_genoux',
    principaux: [qua, abd],
    secondaires: [mol],
    mesure: duree,
    etapes: [
      'Cours sur place en montant les genoux à hauteur de hanches.',
      'Les bras accompagnent.',
      "Reste sur l'avant des pieds.",
    ],
    erreurs: ['Se pencher en arrière.', 'Genoux trop bas.'],
    respiration: rHiit,
    met: 8,
  ),
  ExerciceSport(
    'talons_fesses',
    'Talons-fesses',
    hiit,
    'talons_fesses',
    principaux: [isc],
    secondaires: [mol],
    mesure: duree,
    etapes: [
      'Cours sur place en ramenant les talons vers les fesses.',
      'Le buste droit, les bras accompagnent.',
      'Garde un rythme vif.',
    ],
    erreurs: ['Genoux qui avancent.', 'Se pencher.'],
    respiration: rHiit,
    met: 7,
  ),
  ExerciceSport(
    'patineur',
    'Patineur',
    hiit,
    'patineur',
    principaux: [fes, qua],
    secondaires: [add, mol],
    mesure: duree,
    niveau: inter,
    etapes: [
      'Bondis sur le côté sur une jambe.',
      "L'autre jambe se croise derrière, les bras balancent.",
      "Rebondis de l'autre côté.",
    ],
    erreurs: ['Atterrir genou raide.', 'Genou qui rentre.'],
    respiration: rHiit,
    met: 8,
  ),
  ExerciceSport(
    'saut_groupe',
    'Sauts groupés',
    hiit,
    'saut_groupe',
    principaux: [qua, fes],
    secondaires: [abd, mol],
    niveau: av,
    etapes: [
      'Saute haut en ramenant les genoux vers la poitrine.',
      'Atterris souplement.',
      'Enchaîne sans pause.',
    ],
    erreurs: ['Atterrir raide.', 'Dos rond.'],
    respiration: rHiit,
    intensite: 3,
    met: 10,
  ),
  ExerciceSport(
    'plank_jack',
    'Planche jacks',
    hiit,
    'plank_jack',
    principaux: [abd],
    secondaires: [epa, add],
    mesure: duree,
    niveau: inter,
    etapes: [
      'En planche haute.',
      'Saute pour écarter les pieds, puis rapproche-les.',
      'Le bassin reste stable.',
    ],
    erreurs: ['Bassin qui monte.', 'Épaules qui reculent.'],
    respiration: rHiit,
    met: 8,
  ),
  ExerciceSport(
    'ours',
    "Marche de l'ours",
    hiit,
    'bear_crawl',
    principaux: [abd, epa],
    secondaires: [qua, tri],
    poly: true,
    mesure: duree,
    niveau: inter,
    etapes: [
      'À quatre pattes, genoux décollés.',
      'Avance main et pied opposés ensemble.',
      'Garde le dos plat et les genoux bas.',
    ],
    erreurs: ['Fesses hautes.', 'Pas trop grands.'],
    respiration: rHiit,
    met: 7,
  ),
  ExerciceSport(
    'chenille',
    'Chenille',
    hiit,
    'chenille',
    principaux: [isc, epa],
    secondaires: [abd, pec],
    poly: true,
    etapes: [
      'Debout, penche-toi et pose les mains au sol.',
      "Avance les mains jusqu'en planche.",
      'Ramène les pieds vers les mains, jambes tendues.',
    ],
    erreurs: ['Plier les genoux trop tôt.', "Bassin qui s'affaisse."],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'thruster',
    'Squat développé aux haltères',
    muscu,
    'thruster',
    principaux: [qua, epa],
    secondaires: [fes, tri, abd],
    materiel: {hal},
    poly: true,
    niveau: inter,
    etapes: [
      "Haltères à hauteur d'épaules.",
      'Descends en squat.',
      "En remontant, pousse les haltères au-dessus de la tête d'un seul "
          'élan.',
    ],
    erreurs: ['Cambrer en haut.', 'Squat trop haut.'],
    respiration: rHiit,
    intensite: 3,
    met: 8,
  ),
  ExerciceSport(
    'boxe',
    'Boxe dans le vide',
    hiit,
    'boxe',
    principaux: [epa],
    secondaires: [abd, obl, mol],
    mesure: duree,
    etapes: [
      'En garde, poings au menton, sautille léger.',
      'Enchaîne directs et crochets, en tournant les hanches.',
      'Ramène vite la main en garde.',
    ],
    erreurs: ['Bras tendus verrouillés.', 'Baisser la garde.'],
    respiration: rHiit,
    met: 7.8,
  ),
  ExerciceSport(
    'corde_a_sauter',
    'Corde à sauter',
    cardio,
    'corde',
    principaux: [mol],
    secondaires: [qua, epa],
    materiel: {corde},
    mesure: duree,
    etapes: [
      'Coudes près du corps, les poignets font tourner la corde.',
      "Petits sauts sur l'avant des pieds.",
      'Regard devant, épaules relâchées.',
    ],
    erreurs: ['Sauter trop haut.', 'Tourner avec les bras.'],
    respiration: rCardio,
    met: 11,
  ),
  ExerciceSport(
    'corde_double',
    'Double saut à la corde',
    cardio,
    'corde',
    principaux: [mol],
    secondaires: [qua, epa, avb],
    materiel: {corde},
    mesure: duree,
    niveau: av,
    etapes: [
      'Saute un peu plus haut.',
      'La corde passe deux fois sous les pieds à chaque saut.',
      'Poignets rapides, corps gainé.',
    ],
    erreurs: ['Plier les genoux en arrière.', 'Bras trop larges.'],
    respiration: rCardio,
    intensite: 2,
    met: 12,
  ),
  // ── Cardio ───────────────────────────────────────────────────────────────
  ExerciceSport(
    'course',
    'Course à pied',
    cardio,
    'course',
    principaux: [qua, mol],
    secondaires: [isc, fes],
    mesure: duree,
    etapes: [
      'Pars lentement\u00a0: tu dois pouvoir parler.',
      'Pose le pied sous toi, pas loin devant.',
      "Les bras balancent d'avant en arrière, épaules basses.",
    ],
    erreurs: ['Partir trop vite.', 'Grandes enjambées talon en premier.'],
    respiration: rCardio,
    met: 9.8,
  ),
  ExerciceSport(
    'course_sur_place',
    'Course sur place',
    cardio,
    'course_sur_place',
    principaux: [qua, mol],
    mesure: duree,
    etapes: [
      "Cours sur place, sur l'avant des pieds.",
      'Bras actifs, genoux modérés.',
      'Accélère par moments.',
    ],
    erreurs: ['Talons qui frappent.', 'Se pencher.'],
    respiration: rCardio,
    met: 8,
  ),
  ExerciceSport(
    'marche',
    'Marche',
    cardio,
    'marche',
    principaux: [mol, qua],
    secondaires: [fes],
    mesure: duree,
    etapes: [
      "Marche d'un pas régulier, le buste droit.",
      'Déroule le pied du talon aux orteils.',
      'Balance les bras naturellement.',
    ],
    erreurs: ['Regarder ses pieds.', 'Pas trop longs.'],
    respiration: rCardio,
    met: 3.5,
  ),
  ExerciceSport(
    'marche_rapide',
    'Marche rapide',
    cardio,
    'marche_rapide',
    principaux: [mol, qua],
    secondaires: [fes, isc],
    mesure: duree,
    etapes: [
      'Marche vite, comme si tu étais en retard.',
      'Bras pliés à 90°, ils rythment le pas.',
      'Tu es un peu essoufflé, mais tu peux parler.',
    ],
    erreurs: ['Pencher le buste.', "Allonger le pas au lieu de l'accélérer."],
    respiration: rCardio,
    met: 5,
  ),
  ExerciceSport(
    'escaliers',
    "Montée d'escaliers",
    cardio,
    'step_up',
    principaux: [qua, fes],
    secondaires: [mol],
    mesure: duree,
    etapes: [
      "Monte les marches une à une, d'un bon rythme.",
      'Pose tout le pied.',
      'Redescends calmement en te tenant à la rampe.',
    ],
    erreurs: ['Se hisser à la rampe.', 'Monter sur la pointe.'],
    respiration: rCardio,
    met: 8,
  ),
  ExerciceSport(
    'velo',
    'Vélo',
    cardio,
    'velo',
    principaux: [qua],
    secondaires: [fes, mol, isc],
    materiel: {velo},
    mesure: duree,
    etapes: [
      'Selle réglée\u00a0: jambe presque tendue en bas.',
      'Pédale rond, à une cadence régulière.',
      'Change de vitesse avant que ça devienne dur.',
    ],
    erreurs: ['Selle trop basse.', 'Grosse vitesse à faible cadence.'],
    respiration: rCardio,
    met: 7.5,
  ),
  ExerciceSport(
    'footing',
    'Footing lent',
    cardio,
    'course',
    principaux: [qua, mol],
    secondaires: [fes],
    mesure: duree,
    etapes: [
      'Cours très lentement\u00a0: tu peux tenir une conversation.',
      'Petites foulées, pied sous le bassin.',
      "Si tu t'essouffles, marche une minute, puis repars.",
    ],
    erreurs: ['Aller trop vite dès le départ.', 'Serrer les poings.'],
    respiration: rCardio,
    met: 7,
  ),
  ExerciceSport(
    'sprints',
    'Sprints',
    cardio,
    'sprints',
    principaux: [qua, isc, fes],
    secondaires: [mol],
    mesure: duree,
    niveau: av,
    etapes: [
      "Bien échauffé, accélère progressivement jusqu'à ta vitesse maximale.",
      'Tiens 10 à 20 secondes, genoux hauts, bras puissants.',
      'Récupère en marchant avant le suivant.',
    ],
    erreurs: ['Sprinter à froid.', 'Se crisper des épaules.'],
    respiration: rCardio,
    intensite: 3,
    met: 12,
  ),
  ExerciceSport(
    'randonnee',
    'Randonnée',
    cardio,
    'marche_cote',
    principaux: [qua, fes, mol],
    secondaires: [isc],
    mesure: duree,
    etapes: [
      'Des chaussures qui tiennent la cheville.',
      'En montée, raccourcis le pas\u00a0; en descente, genoux souples.',
      'Bois régulièrement.',
    ],
    erreurs: ['Partir trop vite en montée.', 'Oublier de boire.'],
    respiration: rCardio,
    met: 6,
  ),
  ExerciceSport(
    'marche_cote',
    'Marche en côte',
    cardio,
    'marche_cote',
    principaux: [fes, mol],
    secondaires: [qua, isc],
    mesure: duree,
    etapes: [
      'Choisis une pente régulière.',
      "Buste légèrement penché vers l'avant, pas courts.",
      "Pousse bien sur l'avant du pied.",
    ],
    erreurs: ['Se pencher depuis le dos.', 'Pas trop longs.'],
    respiration: rCardio,
    met: 6,
  ),
  ExerciceSport(
    'velo_interieur',
    "Vélo d'intérieur",
    cardio,
    'velo',
    principaux: [qua],
    secondaires: [fes, mol],
    materiel: {velo},
    mesure: duree,
    etapes: [
      'Règle la selle à hauteur de hanche.',
      'Échauffe-toi cinq minutes en douceur.',
      'Alterne cadence souple et résistance plus dure.',
    ],
    erreurs: ['Selle trop basse.', 'Rebondir sur la selle.'],
    respiration: rCardio,
    met: 7,
  ),
];
