// lib/modele/sports/catalogue/jambes.dart
//
// La banque : JAMBES ET FESSIERS — squats, fentes, charnières de hanche,
// ponts, mollets.

import 'raccourcis.dart';

const List<ExerciceSport> exercicesJambes = [
  // ── Squats ───────────────────────────────────────────────────────────────
  ExerciceSport(
    'squat_chaise',
    'Squat sur chaise',
    pdc,
    'squat_chaise',
    principaux: [qua, fes],
    secondaires: [isc],
    materiel: {chaise},
    poly: true,
    etapes: [
      'Debout devant une chaise, pieds à largeur de hanches.',
      "Recule les hanches et descends jusqu'à effleurer l'assise.",
      'Sans te laisser tomber, pousse dans les talons pour te relever.',
    ],
    erreurs: [
      "S'asseoir lourdement et se relever d'un élan.",
      "Genoux qui rentrent vers l'intérieur.",
    ],
    respiration: rJambes,
  ),
  ExerciceSport(
    'squat',
    'Squat',
    pdc,
    'squat',
    principaux: [qua, fes],
    secondaires: [isc, abd],
    poly: true,
    etapes: [
      'Pieds un peu plus larges que les hanches, pointes légèrement ouvertes.',
      'Recule les hanches et plie les genoux, le buste fier, les bras devant.',
      'Descends au moins cuisses parallèles au sol, talons collés.',
      "Pousse le sol pour remonter, genoux dans l'axe des pieds.",
    ],
    erreurs: [
      'Talons qui décollent.',
      "Genoux qui s'effondrent vers l'intérieur.",
      "Dos qui s'arrondit en bas.",
    ],
    respiration: rJambes,
  ),
  ExerciceSport(
    'squat_pause',
    'Squat avec pause',
    pdc,
    'squat_pause',
    principaux: [qua, fes],
    secondaires: [isc, abd],
    poly: true,
    niveau: inter,
    etapes: [
      "Comme un squat, pieds à largeur d'épaules.",
      'Descends lentement et tiens trois secondes tout en bas.',
      "Remonte d'un coup, sans rebond.",
    ],
    erreurs: [
      'Se relâcher pendant la pause.',
      "Rebondir au lieu de repartir de l'arrêt.",
    ],
    respiration: rJambes,
  ),
  ExerciceSport(
    'squat_tempo',
    'Squat tempo',
    pdc,
    'squat_tempo',
    principaux: [qua, fes],
    secondaires: [isc],
    poly: true,
    etapes: [
      'Descends en comptant trois secondes.',
      'Une seconde tout en bas.',
      'Remonte en une seconde, avec énergie.',
    ],
    erreurs: ['Accélérer quand ça brûle.', 'Talons qui décollent.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'squat_sumo',
    'Squat sumo',
    pdc,
    'squat_sumo',
    principaux: [add, fes, qua],
    poly: true,
    etapes: [
      "Pieds très écartés, pointes ouvertes vers l'extérieur.",
      "Descends droit, les genoux poussés vers l'extérieur.",
      'Remonte en serrant les fessiers.',
    ],
    erreurs: ['Genoux qui rentrent.', "Buste qui bascule vers l'avant."],
    respiration: rJambes,
  ),
  ExerciceSport(
    'squat_sumo_haltere',
    "Squat sumo à l'haltère",
    muscu,
    'squat_sumo_charge',
    principaux: [add, fes, qua],
    secondaires: [avb],
    materiel: {hal},
    poly: true,
    etapes: [
      'Tiens un haltère par une extrémité, bras tendus entre les jambes.',
      'Pieds très écartés, pointes ouvertes.',
      "Descends jusqu'à ce que l'haltère frôle le sol, puis remonte.",
    ],
    erreurs: ['Dos rond en bas.', 'Genoux qui rentrent.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_goblet',
    'Squat goblet',
    muscu,
    'squat_goblet',
    principaux: [qua, fes],
    secondaires: [abd, isc],
    materiel: {hal},
    poly: true,
    etapes: [
      'Tiens un haltère debout contre la poitrine, coudes sous les mains.',
      'Descends entre tes genoux, le buste droit.',
      "Les coudes frôlent l'intérieur des genoux en bas.",
      'Remonte en poussant dans tout le pied.',
    ],
    erreurs: [
      "Laisser l'haltère tirer le buste vers l'avant.",
      'Descendre à moitié.',
    ],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_goblet_kb',
    'Squat goblet à la kettlebell',
    muscu,
    'squat_goblet',
    principaux: [qua, fes],
    secondaires: [abd, avb],
    materiel: {kb},
    poly: true,
    etapes: [
      'Tiens la kettlebell par les cornes, contre la poitrine.',
      'Descends le buste droit, les coudes entre les genoux.',
      'Remonte en poussant dans les talons.',
    ],
    erreurs: ['Buste qui plonge.', 'Talons qui décollent.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_halteres',
    'Squat aux haltères',
    muscu,
    'squat_halteres',
    principaux: [qua, fes],
    secondaires: [isc, avb],
    materiel: {hal},
    poly: true,
    etapes: [
      'Un haltère dans chaque main, bras le long du corps.',
      'Descends en reculant les hanches, les haltères à la verticale.',
      'Remonte en gardant le dos plat.',
    ],
    erreurs: ["Épaules qui s'enroulent.", "Dos qui s'arrondit."],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_barre',
    'Squat à la barre',
    muscu,
    'squat_barre',
    principaux: [qua, fes],
    secondaires: [isc, lom, abd],
    materiel: {bar},
    poly: true,
    niveau: inter,
    etapes: [
      'Barre posée sur le haut du dos, pas sur la nuque.',
      'Serre les omoplates, gonfle le ventre, sors du support.',
      'Descends sous la parallèle en gardant la barre au-dessus du milieu '
          'du pied.',
      'Remonte hanches et épaules ensemble.',
    ],
    erreurs: [
      'Les hanches remontent avant les épaules.',
      'Genoux qui rentrent.',
      'Dos rond en bas.',
    ],
    respiration: rJambes,
    intensite: 3,
  ),
  ExerciceSport(
    'squat_avant',
    'Squat avant',
    muscu,
    'squat_avant',
    principaux: [qua],
    secondaires: [fes, abd, lom],
    materiel: {bar},
    poly: true,
    niveau: av,
    etapes: [
      "La barre sur l'avant des épaules, coudes hauts.",
      'Descends le buste très droit.',
      'Remonte en gardant les coudes levés.',
    ],
    erreurs: [
      'Coudes qui tombent\u00a0: la barre roule.',
      "Buste qui s'incline.",
    ],
    respiration: rJambes,
    intensite: 3,
  ),
  ExerciceSport(
    'squat_saute',
    'Squat sauté',
    hiit,
    'squat_saute',
    principaux: [qua, fes],
    secondaires: [mol],
    poly: true,
    niveau: inter,
    etapes: [
      'Descends en squat, les bras en arrière.',
      'Jaillis vers le haut en lançant les bras.',
      "Atterris souplement sur l'avant des pieds et redescends.",
    ],
    erreurs: [
      'Atterrir jambes tendues.',
      'Genoux qui rentrent à la réception.',
    ],
    respiration: rHiit,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_bulgare',
    'Squat bulgare',
    pdc,
    'squat_bulgare',
    principaux: [qua, fes],
    secondaires: [add, isc],
    materiel: {chaise},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      "Dos à une chaise, pose le dessus d'un pied sur l'assise.",
      'Le pied avant loin devant, descends droit.',
      "Le genou arrière frôle le sol, puis pousse sur le pied avant.",
    ],
    erreurs: [
      'Pied avant trop près\u00a0: le genou dépasse beaucoup.',
      'Pousser avec la jambe arrière.',
    ],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_bulgare_halteres',
    'Squat bulgare aux haltères',
    muscu,
    'squat_bulgare',
    principaux: [qua, fes],
    secondaires: [add, avb],
    materiel: {hal, chaise},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Un haltère dans chaque main, le pied arrière sur une chaise.',
      "Descends droit jusqu'à frôler le sol du genou.",
      'Remonte en poussant sur le talon avant.',
    ],
    erreurs: ["Buste qui s'effondre.", 'Genou avant qui rentre.'],
    respiration: rJambes,
    intensite: 3,
  ),
  ExerciceSport(
    'squat_une_jambe_chaise',
    'Squat une jambe sur chaise',
    pdc,
    'squat_une_jambe_chaise',
    principaux: [qua, fes],
    secondaires: [abd],
    materiel: {chaise},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      "Debout sur une jambe devant une chaise, l'autre tendue devant.",
      "Descends jusqu'à t'asseoir en douceur.",
      'Relève-toi sur la même jambe, sans élan.',
    ],
    erreurs: ['Se laisser tomber.', 'Genou qui rentre.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'pistol',
    'Squat pistol',
    pdc,
    'squat_une_jambe',
    principaux: [qua, fes],
    secondaires: [abd, mol],
    poly: true,
    niveau: av,
    parCote: true,
    etapes: [
      "Sur une jambe, l'autre tendue devant, les bras en avant.",
      'Descends tout en bas, talon au sol.',
      "Remonte sans poser l'autre pied.",
    ],
    erreurs: ['Talon qui décolle.', "Dos qui s'arrondit en bas."],
    respiration: rJambes,
    intensite: 3,
  ),
  ExerciceSport(
    'chaise_murale',
    'Chaise murale',
    gain,
    'chaise_murale',
    principaux: [qua],
    secondaires: [fes],
    mesure: duree,
    etapes: [
      "Dos contre un mur, glisse jusqu'à cuisses parallèles au sol.",
      'Genoux au-dessus des chevilles.',
      'Tiens, le dos bien collé.',
    ],
    erreurs: ['Genoux au-delà des pointes.', 'Mains sur les cuisses.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'squat_profond_tenu',
    'Squat profond tenu',
    mobi,
    'squat_tenu',
    principaux: [add, fes],
    secondaires: [mol],
    mesure: duree,
    etapes: [
      'Descends en squat le plus bas possible, talons au sol.',
      "Coudes contre l'intérieur des genoux, pousse-les doucement.",
      'Reste, le dos long.',
    ],
    erreurs: ['Talons qui décollent.', 'Dos affaissé.'],
    respiration: rEtirement,
  ),
  // ── Fentes ───────────────────────────────────────────────────────────────
  ExerciceSport(
    'fente_arriere',
    'Fente arrière',
    pdc,
    'fente',
    principaux: [qua, fes],
    secondaires: [isc, add],
    poly: true,
    parCote: true,
    etapes: [
      'Debout, fais un grand pas en arrière.',
      "Descends jusqu'à ce que le genou arrière frôle le sol.",
      'Pousse sur le talon avant pour revenir.',
    ],
    erreurs: ['Genou avant qui rentre.', 'Buste penché.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'fente_avant',
    'Fente avant',
    pdc,
    'fente_avant',
    principaux: [qua, fes],
    secondaires: [isc, add],
    poly: true,
    parCote: true,
    etapes: [
      'Fais un grand pas en avant, le buste droit.',
      'Descends les deux genoux pliés à angle droit.',
      'Repousse le sol pour revenir aux pieds joints.',
    ],
    erreurs: ['Pas trop court.', 'Talon avant qui décolle.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'fente_marchee',
    'Fentes marchées',
    pdc,
    'fente_marchee',
    principaux: [qua, fes],
    secondaires: [isc, add, mol],
    poly: true,
    niveau: inter,
    etapes: [
      "Enchaîne les fentes en avançant, une jambe puis l'autre.",
      'Le genou arrière frôle le sol à chaque pas.',
      'Garde le buste droit, le regard devant.',
    ],
    erreurs: ['Pas trop courts.', "Perdre l'équilibre en tournant."],
    respiration: rJambes,
  ),
  ExerciceSport(
    'fente_halteres',
    'Fente aux haltères',
    muscu,
    'fente_halteres',
    principaux: [qua, fes],
    secondaires: [isc, avb],
    materiel: {hal},
    poly: true,
    parCote: true,
    etapes: [
      'Un haltère dans chaque main, bras le long du corps.',
      'Grand pas en arrière, descends droit.',
      'Reviens en poussant sur la jambe avant.',
    ],
    erreurs: ['Épaules enroulées.', 'Genou qui cogne le sol.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'fente_marchee_halteres',
    'Fentes marchées aux haltères',
    muscu,
    'fente_marchee_halteres',
    principaux: [qua, fes],
    secondaires: [isc, avb, abd],
    materiel: {hal},
    poly: true,
    niveau: inter,
    etapes: [
      'Un haltère dans chaque main.',
      'Avance en fentes, genou arrière frôlant le sol.',
      'Garde le tronc gainé à chaque pas.',
    ],
    erreurs: ['Pas trop courts.', 'Buste qui bascule.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'fente_barre',
    'Fente à la barre',
    muscu,
    'fente_barre',
    principaux: [qua, fes],
    secondaires: [isc, abd],
    materiel: {bar},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Barre sur le haut du dos.',
      'Grand pas en arrière, descends droit.',
      'Reviens sans pencher le buste.',
    ],
    erreurs: ["Perdre l'équilibre\u00a0: pieds trop alignés.", 'Buste penché.'],
    respiration: rJambes,
    intensite: 3,
  ),
  ExerciceSport(
    'fente_sautee',
    'Fente sautée',
    hiit,
    'fente_sautee',
    principaux: [qua, fes],
    secondaires: [mol, isc],
    poly: true,
    niveau: inter,
    etapes: [
      'En fente, genou arrière près du sol.',
      "Saute et change de jambe en l'air.",
      'Atterris souplement directement en fente.',
    ],
    erreurs: ['Atterrir jambes raides.', 'Genou qui tape le sol.'],
    respiration: rHiit,
    intensite: 2,
  ),
  ExerciceSport(
    'fente_laterale',
    'Fente latérale',
    pdc,
    'fente_laterale',
    principaux: [add, qua, fes],
    poly: true,
    parCote: true,
    etapes: [
      'Pieds joints, fais un grand pas sur le côté.',
      "Plie la jambe du pas, l'autre reste tendue.",
      'Pousse pour revenir au centre.',
    ],
    erreurs: ['Talon qui décolle.', "Dos qui s'arrondit."],
    respiration: rJambes,
  ),
  ExerciceSport(
    'fente_laterale_haltere',
    "Fente latérale à l'haltère",
    muscu,
    'fente_laterale_goblet',
    principaux: [add, qua, fes],
    materiel: {hal},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Un haltère contre la poitrine.',
      'Grand pas sur le côté, fesses en arrière.',
      'Reviens au centre en poussant.',
    ],
    erreurs: ["Genou qui dépasse vers l'intérieur.", 'Buste effondré.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'fente_croisee',
    'Fente croisée',
    pdc,
    'fente_croisee',
    principaux: [fes, qua],
    secondaires: [add],
    poly: true,
    parCote: true,
    etapes: [
      "Croise une jambe en arrière de l'autre, en diagonale.",
      'Descends droit, le bassin face à toi.',
      'Remonte en serrant le fessier de la jambe avant.',
    ],
    erreurs: ['Bassin qui tourne.', 'Genou avant qui rentre.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'step_up',
    'Montée sur chaise',
    pdc,
    'step_up',
    principaux: [qua, fes],
    secondaires: [mol],
    materiel: {chaise},
    poly: true,
    parCote: true,
    etapes: [
      'Face à une chaise stable ou une marche.',
      'Pose tout le pied dessus et monte en poussant sur ce pied.',
      'Redescends lentement, la même jambe travaille.',
    ],
    erreurs: [
      "Prendre de l'élan avec la jambe du bas.",
      'Genou qui rentre en montant.',
    ],
    respiration: rJambes,
  ),
  ExerciceSport(
    'step_up_halteres',
    'Montée sur chaise aux haltères',
    muscu,
    'step_up',
    principaux: [qua, fes],
    secondaires: [mol, avb],
    materiel: {hal, chaise},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Un haltère dans chaque main.',
      'Monte en poussant sur le pied posé.',
      'Redescends en contrôlant.',
    ],
    erreurs: ['Pousser avec le pied du bas.', 'Buste penché.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'box_jump',
    'Saut sur caisse',
    hiit,
    'box_jump',
    principaux: [qua, fes],
    secondaires: [mol],
    materiel: {chaise},
    poly: true,
    niveau: av,
    etapes: [
      'Face à une caisse stable (jamais une chaise qui bascule).',
      'Descends en quart de squat, lance les bras, saute.',
      'Atterris doucement, genoux fléchis, puis redescends en marchant.',
    ],
    erreurs: ['Atterrir jambes tendues.', 'Sauter pour redescendre.'],
    respiration: rHiit,
    intensite: 2,
  ),
  // ── Charnière de hanche ──────────────────────────────────────────────────
  ExerciceSport(
    'souleve_roumain',
    'Soulevé de terre roumain aux haltères',
    muscu,
    'souleve_roumain',
    principaux: [isc, fes],
    secondaires: [lom, avb],
    materiel: {hal},
    poly: true,
    etapes: [
      'Debout, un haltère dans chaque main devant les cuisses.',
      'Genoux souples, recule les hanches, les haltères frôlent les jambes.',
      "Descends jusqu'à sentir l'arrière des cuisses tirer, dos plat.",
      "Ramène les hanches vers l'avant en serrant les fessiers.",
    ],
    erreurs: [
      'Dos rond.',
      'Plier les genoux comme un squat.',
      "Haltères qui s'éloignent des jambes.",
    ],
    respiration: rCharniere,
    intensite: 2,
  ),
  ExerciceSport(
    'souleve_roumain_barre',
    'Soulevé de terre roumain à la barre',
    muscu,
    'souleve_roumain_barre',
    principaux: [isc, fes],
    secondaires: [lom, avb],
    materiel: {bar},
    poly: true,
    niveau: inter,
    etapes: [
      'La barre en main, bras tendus.',
      'Recule les hanches, la barre glisse le long des cuisses.',
      "Remonte en poussant les hanches vers l'avant.",
    ],
    erreurs: ['Dos rond.', 'Barre loin des jambes.'],
    respiration: rCharniere,
    intensite: 3,
  ),
  ExerciceSport(
    'souleve_roumain_kb',
    'Soulevé de terre roumain à la kettlebell',
    muscu,
    'souleve_roumain_kb',
    principaux: [isc, fes],
    secondaires: [lom],
    materiel: {kb},
    poly: true,
    etapes: [
      'La kettlebell à deux mains devant toi.',
      'Recule les hanches, dos plat.',
      'Remonte en serrant les fessiers.',
    ],
    erreurs: ['Dos rond.', 'Tirer avec les bras.'],
    respiration: rCharniere,
    intensite: 2,
  ),
  ExerciceSport(
    'souleve_une_jambe_pdc',
    'Soulevé une jambe au poids du corps',
    pdc,
    'souleve_une_jambe',
    principaux: [isc, fes],
    secondaires: [lom, mol],
    parCote: true,
    etapes: [
      'Sur une jambe, genou souple.',
      "Bascule le buste en avant, l'autre jambe monte derrière.",
      'Le corps forme une ligne, puis reviens debout.',
    ],
    erreurs: ["Bassin qui s'ouvre sur le côté.", 'Dos rond.'],
    respiration: rCharniere,
  ),
  ExerciceSport(
    'souleve_une_jambe',
    'Soulevé de terre une jambe aux haltères',
    muscu,
    'souleve_une_jambe',
    principaux: [isc, fes],
    secondaires: [lom, avb],
    materiel: {hal},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Un haltère dans chaque main, sur une jambe.',
      'Bascule en avant, la jambe libre monte en ligne avec le dos.',
      "Remonte en serrant le fessier de la jambe d'appui.",
    ],
    erreurs: ['Bassin qui tourne.', "Genou d'appui verrouillé."],
    respiration: rCharniere,
    intensite: 2,
  ),
  ExerciceSport(
    'souleve_terre',
    'Soulevé de terre aux haltères',
    muscu,
    'souleve_terre',
    principaux: [isc, fes, lom],
    secondaires: [qua, tra, avb],
    materiel: {hal},
    poly: true,
    etapes: [
      'Les haltères au sol de chaque côté des pieds.',
      'Hanches en arrière, genoux pliés, dos plat, attrape-les.',
      'Pousse le sol et redresse-toi, hanches et épaules ensemble.',
      "Repose en reculant d'abord les hanches.",
    ],
    erreurs: ['Dos rond.', 'Tirer avec les bras.'],
    respiration: rCharniere,
    intensite: 3,
  ),
  ExerciceSport(
    'souleve_terre_barre',
    'Soulevé de terre à la barre',
    muscu,
    'souleve_terre_barre',
    principaux: [isc, fes, lom],
    secondaires: [qua, dos, tra, avb],
    materiel: {bar},
    poly: true,
    niveau: inter,
    etapes: [
      'La barre au-dessus du milieu des pieds.',
      'Attrape-la, tibias contre la barre, dos plat, épaules au-dessus.',
      'Pousse le sol, la barre remonte collée aux jambes.',
      'Termine debout, fessiers serrés, sans te pencher en arrière.',
    ],
    erreurs: [
      'Dos rond au départ.',
      "Barre qui s'éloigne des jambes.",
      'Cambrer en haut.',
    ],
    respiration: rCharniere,
    intensite: 3,
  ),
  ExerciceSport(
    'souleve_terre_kb',
    'Soulevé de terre à la kettlebell',
    muscu,
    'souleve_terre_kb',
    principaux: [fes, isc],
    secondaires: [qua, lom],
    materiel: {kb},
    poly: true,
    etapes: [
      'La kettlebell entre les pieds.',
      'Hanches en arrière, dos plat, saisis la poignée.',
      'Redresse-toi en poussant le sol.',
    ],
    erreurs: ['Dos rond.', 'Tirer avec les bras.'],
    respiration: rCharniere,
    intensite: 2,
  ),
  ExerciceSport(
    'good_morning',
    'Good morning',
    pdc,
    'good_morning',
    principaux: [isc, lom],
    secondaires: [fes],
    etapes: [
      'Mains derrière la tête, genoux souples.',
      'Bascule le buste en avant en reculant les hanches.',
      'Remonte en serrant les fessiers.',
    ],
    erreurs: ['Dos rond.', 'Descendre trop bas.'],
    respiration: rCharniere,
  ),
  ExerciceSport(
    'swing_kettlebell',
    'Swing à la kettlebell',
    muscu,
    'swing_kettlebell',
    principaux: [fes, isc],
    secondaires: [lom, abd, epa],
    materiel: {kb},
    poly: true,
    niveau: inter,
    etapes: [
      'La kettlebell à deux mains, pieds un peu écartés.',
      'Lance-la entre les jambes en reculant les hanches.',
      "Claque les hanches vers l'avant\u00a0: elle monte à hauteur de poitrine.",
      'Laisse-la redescendre, les bras suivent sans tirer.',
    ],
    erreurs: [
      "Faire un squat au lieu d'une charnière.",
      'Lever la kettlebell avec les bras.',
    ],
    respiration: rHiit,
    intensite: 2,
  ),
  ExerciceSport(
    'swing_haltere',
    "Swing à l'haltère",
    muscu,
    'swing_haltere',
    principaux: [fes, isc],
    secondaires: [lom, abd],
    materiel: {hal},
    poly: true,
    niveau: inter,
    etapes: [
      'Un haltère tenu à deux mains par une extrémité.',
      'Lance-le entre les jambes, hanches en arrière.',
      "Projette les hanches\u00a0: l'haltère monte à hauteur d'épaules.",
    ],
    erreurs: ['Tirer avec les bras.', 'Dos rond en bas.'],
    respiration: rHiit,
    intensite: 2,
  ),
  // ── Ponts ────────────────────────────────────────────────────────────────
  ExerciceSport(
    'pont_fessier',
    'Pont fessier',
    pdc,
    'pont_fessier',
    principaux: [fes],
    secondaires: [isc, lom],
    etapes: [
      'Sur le dos, genoux pliés, pieds à plat près des fesses.',
      'Pousse dans les talons et monte le bassin.',
      'Serre fort les fessiers en haut, épaules-hanches-genoux alignés.',
      'Redescends lentement.',
    ],
    erreurs: ['Cambrer le bas du dos.', 'Pousser sur les pointes.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'pont_une_jambe',
    'Pont fessier une jambe',
    pdc,
    'pont_une_jambe',
    principaux: [fes],
    secondaires: [isc, abd],
    niveau: inter,
    parCote: true,
    etapes: [
      'Sur le dos, une jambe tendue vers le haut.',
      'Pousse dans le talon au sol pour monter le bassin.',
      'Garde le bassin bien horizontal.',
    ],
    erreurs: ['Bassin qui penche.', 'Cambrer.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'hip_thrust',
    'Hip thrust',
    pdc,
    'hip_thrust',
    principaux: [fes],
    secondaires: [isc, qua],
    materiel: {banc},
    poly: true,
    niveau: inter,
    etapes: [
      'Le haut du dos contre un banc ou un canapé.',
      'Pieds à plat, pousse les hanches vers le plafond.',
      'Tibias verticaux en haut, menton rentré.',
    ],
    erreurs: ['Cambrer le bas du dos.', 'Pieds trop loin.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'hip_thrust_haltere',
    "Hip thrust à l'haltère",
    muscu,
    'hip_thrust_haltere',
    principaux: [fes],
    secondaires: [isc, qua],
    materiel: {hal, banc},
    poly: true,
    niveau: inter,
    etapes: [
      'Le haut du dos contre un banc, un haltère sur les hanches.',
      'Monte le bassin en serrant les fessiers.',
      'Tiens une seconde en haut, redescends.',
    ],
    erreurs: ['Cambrer.', 'Regarder le plafond.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'hip_thrust_barre',
    'Hip thrust à la barre',
    muscu,
    'hip_thrust_barre',
    principaux: [fes],
    secondaires: [isc, qua],
    materiel: {bar, banc},
    poly: true,
    niveau: inter,
    etapes: [
      'Barre sur les hanches (protégée), le haut du dos sur un banc.',
      "Pousse les hanches jusqu'à l'horizontale.",
      'Redescends en contrôlant.',
    ],
    erreurs: ['Cambrer.', 'Pousser sur les pointes.'],
    respiration: rJambes,
    intensite: 3,
  ),
  ExerciceSport(
    'donkey_kick',
    'Donkey kick',
    pdc,
    'donkey_kick',
    principaux: [fes],
    secondaires: [isc, abd],
    parCote: true,
    etapes: [
      'À quatre pattes, genou plié à angle droit.',
      'Pousse le talon vers le plafond.',
      'Redescends sans poser le genou.',
    ],
    erreurs: ['Cambrer pour monter plus haut.', 'Bassin qui tourne.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'abduction_couche',
    'Abduction couché sur le côté',
    pdc,
    'abduction_cote',
    principaux: [fes],
    secondaires: [obl],
    parCote: true,
    etapes: [
      "Couché sur le côté, jambes tendues l'une sur l'autre.",
      "Monte la jambe du dessus, pointe du pied vers l'avant.",
      'Redescends lentement.',
    ],
    erreurs: ['Pointe tournée vers le plafond.', "Rouler vers l'arrière."],
    respiration: rJambes,
  ),
  ExerciceSport(
    'marche_laterale_elastique',
    "Marche latérale à l'élastique",
    muscu,
    'marche_laterale',
    principaux: [fes],
    secondaires: [add, qua],
    materiel: {ela},
    etapes: [
      "L'élastique autour des jambes, en quart de squat.",
      'Fais des pas sur le côté sans rapprocher les pieds.',
      "Autant de pas dans l'autre sens.",
    ],
    erreurs: ['Genoux qui rentrent.', 'Se redresser.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'nordic',
    'Nordic curl',
    pdc,
    'nordic',
    principaux: [isc],
    secondaires: [fes],
    niveau: av,
    etapes: [
      'À genoux, les talons calés sous un meuble lourd.',
      'Bascule en avant le plus lentement possible, corps droit.',
      'Rattrape-toi sur les mains, repousse pour remonter.',
    ],
    erreurs: ['Casser aux hanches.', 'Se laisser tomber.'],
    respiration: rJambes,
    intensite: 3,
  ),
  // ── Mollets ──────────────────────────────────────────────────────────────
  ExerciceSport(
    'mollets_debout',
    'Mollets debout',
    pdc,
    'mollets',
    principaux: [mol],
    etapes: [
      'Debout, pieds à largeur de hanches.',
      'Monte le plus haut possible sur la pointe des pieds.',
      'Redescends lentement.',
    ],
    erreurs: ['Rebondir.', 'Plier les genoux.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'mollets_halteres',
    'Mollets aux haltères',
    muscu,
    'mollets',
    principaux: [mol],
    materiel: {hal},
    etapes: [
      'Un haltère dans chaque main.',
      'Monte sur la pointe des pieds, tiens une seconde.',
      'Redescends lentement.',
    ],
    erreurs: ['Rebondir.', 'Amplitude trop courte.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'mollets_marche',
    'Mollets sur une marche',
    pdc,
    'mollets_marche',
    principaux: [mol],
    materiel: {chaise},
    niveau: inter,
    etapes: [
      "L'avant des pieds sur une marche, talons dans le vide.",
      'Laisse descendre les talons, puis monte au maximum.',
      "Tiens-toi à un mur pour l'équilibre.",
    ],
    erreurs: ['Rebondir en bas.', 'Plier les genoux.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'mollets_une_jambe',
    'Mollets une jambe',
    pdc,
    'mollets_une_jambe',
    principaux: [mol],
    materiel: {chaise},
    niveau: inter,
    parCote: true,
    etapes: [
      'Sur une marche, un seul pied.',
      'Descends le talon, puis monte au maximum.',
      'Contrôle la descente.',
    ],
    erreurs: ['Rebondir.', 'Se hisser avec les bras.'],
    respiration: rJambes,
  ),
];
