// lib/modele/sports/catalogue/mobilite.dart
//
// La banque : MOBILITÉ ET ÉTIREMENTS — pour l'échauffement (mobiliser les
// articulations), le retour au calme (étirer les muscles travaillés) et les
// routines express.

import 'raccourcis.dart';

const List<ExerciceSport> exercicesMobilite = [
  // ── Mobilité (échauffement) ──────────────────────────────────────────────
  ExerciceSport(
    'cercles_bras',
    'Cercles de bras',
    mobi,
    'cercles_bras',
    principaux: [epa],
    secondaires: [tra],
    mesure: duree,
    etapes: [
      'Bras tendus sur les côtés.',
      'Dessine de petits cercles, puis de plus grands.',
      'Change de sens à mi-temps.',
    ],
    erreurs: ['Hausser les épaules.', 'Aller trop vite.'],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'rotation_hanches',
    'Rotations de hanches',
    mobi,
    'rotation_hanches',
    principaux: [fes, add],
    secondaires: [lom],
    mesure: duree,
    etapes: [
      'Mains sur les hanches, pieds écartés.',
      'Dessine de grands cercles avec le bassin.',
      'Change de sens à mi-temps.',
    ],
    erreurs: ['Bouger les épaules.', 'Petits cercles.'],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'balancier_jambe',
    'Balancier de jambe',
    mobi,
    'balancier_jambe',
    principaux: [isc],
    secondaires: [fes, qua],
    mesure: duree,
    parCote: true,
    etapes: [
      'Debout sur une jambe, une main contre un mur.',
      "Balance l'autre jambe d'avant en arrière, de plus en plus haut.",
      'Change de jambe à mi-temps.',
    ],
    erreurs: ['Cambrer en arrière.', "Forcer l'amplitude."],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'rotation_thoracique',
    'Rotation thoracique',
    mobi,
    'rotation_thoracique',
    principaux: [dos],
    secondaires: [obl],
    mesure: duree,
    parCote: true,
    etapes: [
      'À quatre pattes, une main derrière la tête.',
      'Tourne le coude vers le plafond en suivant du regard.',
      "Redescends vers le bras d'appui.",
    ],
    erreurs: ['Bouger le bassin.', 'Forcer.'],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'chat_vache',
    'Chat-vache',
    mobi,
    'chat_vache',
    principaux: [lom],
    secondaires: [abd, dos],
    mesure: duree,
    etapes: [
      'À quatre pattes, mains sous les épaules.',
      'Inspire en creusant le dos, regard devant.',
      'Souffle en arrondissant le dos, menton rentré.',
    ],
    erreurs: ['Aller trop vite.', 'Plier les bras.'],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'haussements_epaules',
    "Haussements d'épaules",
    mobi,
    'shrug',
    principaux: [tra],
    mesure: duree,
    etapes: [
      'Debout ou assis, bras relâchés.',
      'Monte les épaules vers les oreilles, puis laisse-les tomber.',
      "Termine par des rotations vers l'arrière.",
    ],
    erreurs: ['Crisper la mâchoire.', 'Retenir son souffle.'],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'fente_basse_rotation',
    'Fente basse avec rotation',
    mobi,
    'fente_basse_rotation',
    principaux: [fes, add],
    secondaires: [qua, dos],
    mesure: duree,
    niveau: inter,
    parCote: true,
    etapes: [
      'En fente, le genou arrière au sol.',
      "Pose la main opposée au sol, ouvre l'autre bras vers le plafond.",
      'Reviens, change de côté.',
    ],
    erreurs: ['Genou avant qui rentre.', 'Bloquer la respiration.'],
    respiration: rMobilite,
  ),
  // ── Étirements (retour au calme) ─────────────────────────────────────────
  ExerciceSport(
    'flexion_avant',
    'Flexion avant',
    mobi,
    'flexion_avant',
    principaux: [isc],
    secondaires: [lom, mol],
    mesure: duree,
    etapes: [
      'Debout, genoux souples.',
      "Enroule-toi vers l'avant, la tête lourde.",
      'Laisse pendre les bras, respire, remonte lentement.',
    ],
    erreurs: ['Verrouiller les genoux.', 'Rebondir.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'assis_flexion',
    'Pince assise',
    mobi,
    'assis_flexion',
    principaux: [isc],
    secondaires: [lom, mol],
    mesure: duree,
    etapes: [
      'Assis, jambes tendues devant.',
      'Grandis-toi, puis penche-toi depuis les hanches.',
      'Attrape tes tibias ou tes pieds, respire.',
    ],
    erreurs: ['Arrondir le dos pour aller plus loin.', 'Forcer.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_quadriceps',
    'Étirement des quadriceps',
    mobi,
    'etirement_quadriceps',
    principaux: [qua],
    mesure: duree,
    parCote: true,
    etapes: [
      'Debout, attrape ton pied derrière toi.',
      "Genoux côte à côte, pousse légèrement la hanche vers l'avant.",
      'Tiens, change de jambe.',
    ],
    erreurs: ['Genou qui part sur le côté.', 'Cambrer.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_mollet',
    'Étirement des mollets',
    mobi,
    'etirement_mollet',
    principaux: [mol],
    mesure: duree,
    parCote: true,
    etapes: [
      'Mains contre un mur, une jambe tendue loin derrière.',
      'Talon arrière au sol, plie le genou avant.',
      'Tiens, change de jambe.',
    ],
    erreurs: ['Talon qui décolle.', "Pied tourné vers l'extérieur."],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'fente_basse',
    'Étirement des fléchisseurs de hanche',
    mobi,
    'fente_basse',
    principaux: [qua],
    secondaires: [abd],
    mesure: duree,
    parCote: true,
    etapes: [
      'En fente, le genou arrière posé au sol.',
      'Avance doucement le bassin, le buste droit.',
      'Monte le bras du côté étiré.',
    ],
    erreurs: ['Cambrer.', 'Genou avant au-delà du pied.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_fessier',
    'Étirement des fessiers',
    mobi,
    'etirement_fessier',
    principaux: [fes],
    mesure: duree,
    parCote: true,
    etapes: [
      'Sur le dos, cheville croisée sur le genou opposé.',
      'Ramène les deux jambes vers toi.',
      'Tiens, change de côté.',
    ],
    erreurs: ['Décoller la tête.', 'Tirer trop fort.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'pigeon',
    'Pigeon',
    mobi,
    'pigeon',
    principaux: [fes],
    secondaires: [qua, add],
    mesure: duree,
    niveau: inter,
    parCote: true,
    etapes: [
      "Une jambe pliée devant, l'autre tendue derrière.",
      'Bassin de face, penche-toi en avant.',
      'Respire, change de côté.',
    ],
    erreurs: ['Bassin de travers.', 'Douleur au genou\u00a0: arrête.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'papillon',
    'Papillon',
    mobi,
    'papillon',
    principaux: [add],
    mesure: duree,
    etapes: [
      "Assis, plantes des pieds l'une contre l'autre.",
      'Laisse tomber les genoux vers le sol.',
      'Grandis le dos, penche-toi un peu.',
    ],
    erreurs: ['Appuyer fort sur les genoux.', 'Dos rond.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_adducteurs',
    'Étirement des adducteurs',
    mobi,
    'etirement_adducteurs',
    principaux: [add],
    mesure: duree,
    parCote: true,
    etapes: [
      'Pieds très écartés, plie une jambe.',
      "L'autre reste tendue, pointe vers le haut.",
      'Tiens, change de côté.',
    ],
    erreurs: ['Dos rond.', 'Genou plié qui rentre.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'posture_enfant',
    "Posture de l'enfant",
    mobi,
    'enfant',
    principaux: [dos, lom],
    secondaires: [epa],
    mesure: duree,
    etapes: [
      'À genoux, assieds-toi sur les talons.',
      'Allonge les bras devant, front au sol.',
      'Respire dans le dos.',
    ],
    erreurs: ['Forcer sur les genoux.', 'Tenir les épaules crispées.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'cobra',
    'Cobra',
    mobi,
    'cobra',
    principaux: [abd],
    secondaires: [lom, pec],
    mesure: duree,
    etapes: [
      'À plat ventre, mains sous les épaules.',
      'Pousse doucement pour décoller la poitrine, hanches au sol.',
      'Épaules basses, respire.',
    ],
    erreurs: ["Pousser jusqu'à la douleur.", 'Hausser les épaules.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'chien_tete_bas',
    'Chien tête en bas',
    mobi,
    'chien_tete_bas',
    principaux: [isc, mol],
    secondaires: [epa, dos],
    mesure: duree,
    etapes: [
      'Depuis quatre pattes, monte les fesses vers le plafond.',
      'Pousse le sol, le dos long.',
      'Pédale doucement avec les talons.',
    ],
    erreurs: ['Dos rond.', 'Épaules aux oreilles.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_pectoraux',
    'Étirement des pectoraux',
    mobi,
    'etirement_pectoraux',
    principaux: [pec],
    secondaires: [epa, bic],
    mesure: duree,
    parCote: true,
    etapes: [
      "L'avant-bras contre un cadre de porte, coude à hauteur d'épaule.",
      'Avance doucement le buste.',
      'Tiens, change de côté.',
    ],
    erreurs: ['Cambrer.', "Forcer sur l'épaule."],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_triceps',
    'Étirement des triceps',
    mobi,
    'etirement_triceps',
    principaux: [tri],
    secondaires: [epa],
    mesure: duree,
    parCote: true,
    etapes: [
      'Un bras plié derrière la tête.',
      "L'autre main pousse doucement le coude.",
      'Tiens, change de bras.',
    ],
    erreurs: ['Pencher la tête.', 'Cambrer.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_epaule',
    "Étirement de l'épaule",
    mobi,
    'etirement_epaule',
    principaux: [epa],
    secondaires: [dos],
    mesure: duree,
    parCote: true,
    etapes: [
      'Passe un bras tendu devant la poitrine.',
      "L'autre bras le ramène contre toi.",
      'Épaules basses, tiens, change.',
    ],
    erreurs: ["Hausser l'épaule.", 'Tourner le buste.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'torsion_couchee',
    'Torsion couchée',
    mobi,
    'torsion_couchee',
    principaux: [obl, lom],
    secondaires: [fes],
    mesure: duree,
    parCote: true,
    etapes: [
      'Sur le dos, bras en croix.',
      "Laisse tomber les genoux pliés d'un côté.",
      'Les épaules restent au sol, change de côté.',
    ],
    erreurs: ['Épaule qui décolle.', 'Forcer.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'flexion_laterale',
    'Flexion latérale',
    mobi,
    'flexion_laterale',
    principaux: [obl],
    secondaires: [dos],
    mesure: duree,
    parCote: true,
    etapes: [
      'Debout, un bras au-dessus de la tête.',
      'Penche-toi sur le côté opposé.',
      'Tiens, change de côté.',
    ],
    erreurs: ['Se pencher en avant.', 'Bloquer le souffle.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'genoux_poitrine',
    'Genoux à la poitrine',
    mobi,
    'genoux_poitrine',
    principaux: [lom],
    secondaires: [fes],
    mesure: duree,
    etapes: [
      'Sur le dos, ramène les genoux contre la poitrine.',
      'Enlace-les, berce-toi doucement.',
      'Relâche la nuque.',
    ],
    erreurs: ['Décoller la tête.', 'Tirer fort.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'jambes_mur',
    'Jambes au mur',
    mobi,
    'jambes_mur',
    principaux: [isc],
    secondaires: [mol, lom],
    mesure: duree,
    etapes: [
      "Allongé, les fesses près d'un mur.",
      'Pose les jambes tendues contre le mur.',
      'Bras relâchés, respire lentement.',
    ],
    erreurs: ['Fesses trop loin du mur.', 'Crisper les épaules.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'respiration_ventrale',
    'Respiration ventrale',
    mobi,
    'respiration',
    principaux: [abd],
    mesure: duree,
    etapes: [
      'Allongé, genoux pliés, une main sur le ventre.',
      'Inspire par le nez en gonflant le ventre sur quatre temps.',
      'Souffle par la bouche sur six temps.',
    ],
    erreurs: ['Monter les épaules.', 'Respirer trop vite.'],
    respiration: rEtirement,
  ),
];
