// lib/modele/sports/catalogue/poussee.dart
//
// La banque : POUSSÉE — pectoraux, épaules, triceps (pompes, développés,
// élévations, dips, extensions).

import 'raccourcis.dart';

const List<ExerciceSport> exercicesPoussee = [
  // ── Pompes ───────────────────────────────────────────────────────────────
  ExerciceSport(
    'pompe_murale',
    'Pompes contre le mur',
    pdc,
    'pompe_mur',
    principaux: [pec],
    secondaires: [tri, epa],
    poly: true,
    etapes: [
      "Face à un mur, mains à hauteur d'épaules, un peu plus larges.",
      'Recule les pieds, le corps droit et gainé.',
      "Plie les coudes jusqu'à approcher le nez du mur, puis repousse.",
    ],
    erreurs: ['Fesses en arrière.', "Coudes écartés à l'horizontale."],
    respiration: rPousser,
  ),
  ExerciceSport(
    'pompe_inclinee',
    'Pompes inclinées',
    pdc,
    'pompe_inclinee',
    principaux: [pec],
    secondaires: [tri, epa, abd],
    materiel: {chaise},
    poly: true,
    etapes: [
      'Mains sur une chaise calée contre un mur, ou sur une table.',
      'Le corps droit de la tête aux talons.',
      "Descends la poitrine vers l'appui, puis repousse.",
    ],
    erreurs: ["Bassin qui s'affaisse.", 'Tête qui plonge.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'pompe_genoux',
    'Pompes sur les genoux',
    pdc,
    'pompe_genoux',
    principaux: [pec],
    secondaires: [tri, epa],
    poly: true,
    etapes: [
      'Mains au sol sous les épaules, genoux posés.',
      'Hanches alignées avec les épaules et les genoux.',
      'Descends la poitrine près du sol, coudes à 45°, puis repousse.',
    ],
    erreurs: ["Fesses en l'air.", 'Amplitude trop courte.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'pompe',
    'Pompes',
    pdc,
    'pompe',
    principaux: [pec, tri],
    secondaires: [epa, abd],
    poly: true,
    etapes: [
      'En planche haute, mains un peu plus larges que les épaules.',
      'Le corps gainé, droit de la tête aux talons.',
      "Descends jusqu'à frôler le sol de la poitrine, coudes à 45°.",
      "Repousse le sol d'un bloc.",
    ],
    erreurs: [
      'Hanches qui tombent.',
      'Coudes écartés à 90°.',
      'Descendre à moitié.',
    ],
    respiration: rPousser,
  ),
  ExerciceSport(
    'pompe_large',
    'Pompes mains larges',
    pdc,
    'pompe_large',
    principaux: [pec],
    secondaires: [epa, tri],
    poly: true,
    niveau: inter,
    etapes: [
      'Mains nettement plus larges que les épaules.',
      'Descends la poitrine entre les mains.',
      'Repousse sans verrouiller brutalement.',
    ],
    erreurs: ['Épaules qui montent aux oreilles.', 'Bassin qui tombe.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'pompe_diamant',
    'Pompes diamant',
    pdc,
    'pompe_diamant',
    principaux: [tri],
    secondaires: [pec, epa],
    poly: true,
    niveau: inter,
    etapes: [
      'Mains rapprochées sous la poitrine, pouces et index en losange.',
      'Coudes le long du corps en descendant.',
      'Repousse en tendant les bras.',
    ],
    erreurs: ["Coudes qui s'ouvrent.", 'Poignets douloureux\u00a0: élargis.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'pompe_declinee',
    'Pompes déclinées',
    pdc,
    'pompe_declinee',
    principaux: [pec, epa],
    secondaires: [tri, abd],
    materiel: {chaise},
    poly: true,
    niveau: inter,
    etapes: [
      'Les pieds sur une chaise, les mains au sol.',
      "Le corps gainé, la tête dans l'alignement.",
      'Descends le haut de la poitrine vers le sol, puis repousse.',
    ],
    erreurs: ['Cambrer.', 'Mains trop en avant.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'pompe_archer',
    'Pompes archer',
    pdc,
    'pompe_archer',
    principaux: [pec, tri],
    secondaires: [epa, abd],
    poly: true,
    niveau: av,
    parCote: true,
    etapes: [
      'Mains très écartées.',
      "Descends vers une main, l'autre bras reste tendu.",
      'Repousse, alterne les côtés.',
    ],
    erreurs: ['Bassin qui tourne.', 'Bras tendu qui plie.'],
    respiration: rPousser,
    intensite: 3,
  ),
  ExerciceSport(
    'pompe_explosive',
    'Pompes claquées',
    pdc,
    'pompe_claquee',
    principaux: [pec, tri],
    secondaires: [epa],
    poly: true,
    niveau: av,
    etapes: [
      'Descends en pompe, contrôlé.',
      'Repousse le sol si fort que les mains décollent.',
      'Réceptionne-toi coudes souples et enchaîne.',
    ],
    erreurs: ['Atterrir bras tendus.', "Bassin qui s'affaisse."],
    respiration: rHiit,
    intensite: 3,
  ),
  ExerciceSport(
    'pompe_tempo',
    'Pompes tempo',
    pdc,
    'pompe_tempo',
    principaux: [pec, tri],
    secondaires: [epa, abd],
    poly: true,
    niveau: inter,
    etapes: [
      'Descends en trois secondes.',
      'Une seconde tout près du sol.',
      'Remonte en une seconde.',
    ],
    erreurs: ['Accélérer la descente.', 'Hanches qui tombent.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'pompe_pike',
    'Pompes piquées',
    pdc,
    'pike_pushup',
    principaux: [epa],
    secondaires: [tri, tra],
    poly: true,
    niveau: inter,
    etapes: [
      'En V inversé, fesses hautes, mains au sol.',
      'Plie les coudes\u00a0: le haut de la tête descend entre les mains.',
      "Repousse jusqu'aux bras tendus.",
    ],
    erreurs: ['Descendre le nez devant les mains.', "Coudes qui s'ouvrent."],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'pompe_pike_surelevee',
    'Pompes piquées pieds surélevés',
    pdc,
    'pike_sureleve',
    principaux: [epa],
    secondaires: [tri, tra, abd],
    materiel: {chaise},
    poly: true,
    niveau: av,
    etapes: [
      'Les pieds sur une chaise, les hanches au-dessus des mains.',
      'Descends la tête entre les mains.',
      "Repousse jusqu'aux bras tendus.",
    ],
    erreurs: ['Dos rond.', 'Descendre trop vite.'],
    respiration: rPousser,
    intensite: 3,
  ),
  // ── Développés couchés ───────────────────────────────────────────────────
  ExerciceSport(
    'developpe_sol',
    'Développé au sol aux haltères',
    muscu,
    'developpe_sol',
    principaux: [pec, tri],
    secondaires: [epa],
    materiel: {hal},
    poly: true,
    etapes: [
      'Allongé au sol, genoux pliés, un haltère dans chaque main.',
      'Pousse les haltères au-dessus de la poitrine.',
      "Descends jusqu'à poser doucement les coudes au sol, à 45°.",
      'Repousse sans cogner les haltères.',
    ],
    erreurs: ['Laisser tomber les coudes.', "Coudes à l'horizontale."],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_serre_sol',
    'Développé serré au sol',
    muscu,
    'developpe_serre_sol',
    principaux: [tri],
    secondaires: [pec],
    materiel: {hal},
    poly: true,
    etapes: [
      'Allongé au sol, les haltères parallèles, paumes face à face.',
      'Descends, les coudes serrés contre le corps.',
      'Repousse en tendant complètement les bras.',
    ],
    erreurs: ["Coudes qui s'écartent.", 'Rebondir au sol.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_couche',
    'Développé couché aux haltères',
    muscu,
    'developpe_couche',
    principaux: [pec],
    secondaires: [tri, epa],
    materiel: {hal, banc},
    poly: true,
    etapes: [
      'Allongé sur le banc, pieds au sol, omoplates serrées.',
      'Les haltères au-dessus de la poitrine, bras tendus.',
      'Descends de chaque côté de la poitrine, coudes à 45°.',
      'Repousse en rapprochant les haltères.',
    ],
    erreurs: ['Fesses qui décollent.', 'Descendre trop vite.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_couche_barre',
    'Développé couché à la barre',
    muscu,
    'developpe_couche_barre',
    principaux: [pec],
    secondaires: [tri, epa],
    materiel: {bar, banc},
    poly: true,
    niveau: inter,
    etapes: [
      'Yeux sous la barre, omoplates serrées, pieds ancrés.',
      'Descends la barre au bas de la poitrine, contrôlé.',
      'Pousse en arc vers le haut des épaules.',
      'Avec du poids, toujours une personne pour parer.',
    ],
    erreurs: [
      'Rebondir sur la poitrine.',
      'Fesses qui décollent.',
      'Poignets cassés en arrière.',
    ],
    respiration: rPousser,
    intensite: 3,
  ),
  ExerciceSport(
    'developpe_incline',
    'Développé incliné aux haltères',
    muscu,
    'developpe_incline',
    principaux: [pec, epa],
    secondaires: [tri],
    materiel: {hal, banc},
    poly: true,
    niveau: inter,
    etapes: [
      'Le banc incliné à 30°, le dos bien calé.',
      'Pousse les haltères au-dessus du haut de la poitrine.',
      'Descends lentement, coudes sous les poignets.',
    ],
    erreurs: ['Banc trop incliné\u00a0: ce sont les épaules.', 'Cambrer.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_incline_barre',
    'Développé incliné à la barre',
    muscu,
    'developpe_incline_barre',
    principaux: [pec, epa],
    secondaires: [tri],
    materiel: {bar, banc},
    poly: true,
    niveau: inter,
    etapes: [
      'Banc incliné à 30°.',
      'Descends la barre au haut de la poitrine.',
      'Repousse à la verticale des épaules.',
    ],
    erreurs: ['Rebondir.', 'Fesses qui décollent.'],
    respiration: rPousser,
    intensite: 3,
  ),
  ExerciceSport(
    'ecarte_couche',
    'Écarté couché',
    muscu,
    'ecarte_couche',
    principaux: [pec],
    secondaires: [epa],
    materiel: {hal, banc},
    niveau: inter,
    etapes: [
      'Sur le banc, haltères au-dessus de la poitrine, coudes souples.',
      "Ouvre les bras en arc jusqu'à sentir l'étirement.",
      'Referme comme pour enlacer un arbre.',
    ],
    erreurs: ['Descendre trop bas.', 'Plier les bras comme un développé.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'ecarte_sol',
    'Écarté au sol',
    muscu,
    'ecarte_sol',
    principaux: [pec],
    secondaires: [epa],
    materiel: {hal},
    etapes: [
      'Allongé au sol, haltères au-dessus de la poitrine.',
      "Ouvre les bras, coudes souples, jusqu'à effleurer le sol.",
      'Referme en arc.',
    ],
    erreurs: ['Bras tendus verrouillés.', 'Poser les haltères.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'pullover',
    'Pull-over',
    muscu,
    'pullover',
    principaux: [pec, dos],
    secondaires: [tri],
    materiel: {hal, banc},
    niveau: inter,
    etapes: [
      'Allongé, un haltère tenu à deux mains au-dessus de la poitrine.',
      'Descends-le derrière la tête, bras presque tendus.',
      'Ramène-le au-dessus de la poitrine.',
    ],
    erreurs: ['Cambrer fort.', 'Plier les coudes.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'developpe_elastique',
    "Développé à l'élastique",
    muscu,
    'developpe_elastique',
    principaux: [pec],
    secondaires: [tri, epa],
    materiel: {ela},
    poly: true,
    etapes: [
      "L'élastique accroché derrière toi à hauteur de poitrine.",
      'Un pas en avant, pousse les mains devant toi.',
      'Reviens lentement.',
    ],
    erreurs: ['Cambrer.', "Laisser l'élastique claquer."],
    respiration: rPousser,
  ),
  ExerciceSport(
    'ecarte_elastique',
    "Écarté à l'élastique",
    muscu,
    'ecarte_elastique',
    principaux: [pec],
    secondaires: [epa],
    materiel: {ela},
    etapes: [
      "L'élastique derrière toi, bras ouverts.",
      'Ramène les mains devant la poitrine en arc.',
      'Ouvre lentement.',
    ],
    erreurs: ['Plier les bras.', 'Hausser les épaules.'],
    respiration: rPousser,
  ),
  // ── Dips ─────────────────────────────────────────────────────────────────
  ExerciceSport(
    'dips_chaise',
    'Dips sur chaise',
    pdc,
    'dips_banc',
    principaux: [tri],
    secondaires: [pec, epa],
    materiel: {chaise},
    poly: true,
    etapes: [
      "Mains au bord d'une chaise stable, fesses devant, genoux pliés.",
      "Plie les coudes vers l'arrière jusqu'à 90°.",
      "Repousse jusqu'aux bras tendus.",
    ],
    erreurs: ['Épaules qui montent.', 'Descendre trop bas.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'dips_banc',
    'Dips sur banc',
    pdc,
    'dips_banc',
    principaux: [tri],
    secondaires: [pec, epa],
    materiel: {banc},
    poly: true,
    etapes: [
      'Mains au bord du banc, jambes devant.',
      "Plie les coudes vers l'arrière.",
      "Repousse jusqu'aux bras tendus.",
    ],
    erreurs: ["Coudes qui s'ouvrent.", "S'éloigner du banc."],
    respiration: rPousser,
  ),
  ExerciceSport(
    'dips_jambes_tendues',
    'Dips jambes tendues',
    pdc,
    'dips_tendues',
    principaux: [tri],
    secondaires: [pec, epa],
    materiel: {chaise},
    poly: true,
    niveau: inter,
    etapes: [
      'Mains sur la chaise, jambes tendues, talons au sol.',
      "Descends jusqu'à 90° aux coudes.",
      'Remonte sans pousser avec les jambes.',
    ],
    erreurs: ['Épaules en avant.', 'Pousser avec les talons.'],
    respiration: rPousser,
    intensite: 2,
  ),
  // ── Épaules ──────────────────────────────────────────────────────────────
  ExerciceSport(
    'developpe_epaules',
    'Développé épaules aux haltères',
    muscu,
    'developpe_epaules',
    principaux: [epa],
    secondaires: [tri, tra],
    materiel: {hal},
    poly: true,
    etapes: [
      "Debout ou assis, haltères à hauteur d'épaules, paumes devant.",
      'Pousse au-dessus de la tête sans cambrer.',
      'Redescends aux épaules.',
    ],
    erreurs: ['Cambrer le bas du dos.', 'Descendre à moitié.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_arnold',
    'Développé Arnold',
    muscu,
    'developpe_arnold',
    principaux: [epa],
    secondaires: [tri],
    materiel: {hal},
    poly: true,
    niveau: inter,
    etapes: [
      'Haltères devant le visage, paumes vers toi.',
      "Pousse en tournant les paumes vers l'avant.",
      "Redescends en tournant à l'inverse.",
    ],
    erreurs: ['Aller trop vite.', 'Cambrer.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_militaire',
    'Développé militaire à la barre',
    muscu,
    'developpe_militaire',
    principaux: [epa],
    secondaires: [tri, tra, abd],
    materiel: {bar},
    poly: true,
    niveau: inter,
    etapes: [
      'Debout, barre sur le haut de la poitrine, mains un peu plus larges '
          'que les épaules.',
      'Serre les fessiers, pousse la barre au-dessus de la tête.',
      'Passe la tête sous la barre en haut, redescends.',
    ],
    erreurs: ['Cambrer.', 'Barre qui part devant.'],
    respiration: rPousser,
    intensite: 3,
  ),
  ExerciceSport(
    'developpe_kettlebell',
    'Développé à la kettlebell',
    muscu,
    'developpe_kettlebell',
    principaux: [epa],
    secondaires: [tri, abd],
    materiel: {kb},
    poly: true,
    parCote: true,
    etapes: [
      "La kettlebell en position de rack, contre l'épaule.",
      'Pousse-la au-dessus de la tête, poignet droit.',
      'Redescends en contrôlant.',
    ],
    erreurs: ['Pencher le buste.', 'Poignet cassé.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_epaules_elastique',
    "Développé épaules à l'élastique",
    muscu,
    'developpe_epaules_elastique',
    principaux: [epa],
    secondaires: [tri],
    materiel: {ela},
    poly: true,
    etapes: [
      "Debout sur l'élastique, mains à hauteur d'épaules.",
      'Pousse au-dessus de la tête.',
      'Redescends lentement.',
    ],
    erreurs: ['Cambrer.', 'Coudes trop en arrière.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'elevation_laterale',
    'Élévations latérales',
    muscu,
    'elevation_laterale',
    principaux: [epa],
    secondaires: [tra],
    materiel: {hal},
    etapes: [
      'Debout, haltères le long du corps, coudes souples.',
      "Monte les bras sur les côtés jusqu'à l'horizontale.",
      'Redescends lentement.',
    ],
    erreurs: ['Hausser les épaules.', 'Balancer le corps.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'elevation_laterale_elastique',
    "Élévations latérales à l'élastique",
    muscu,
    'elevation_laterale_elastique',
    principaux: [epa],
    materiel: {ela},
    etapes: [
      "Debout sur l'élastique.",
      "Monte les bras sur les côtés jusqu'à l'horizontale.",
      'Redescends en résistant.',
    ],
    erreurs: ['Hausser les épaules.', 'Bras trop tendus.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'elevation_frontale',
    'Élévations frontales',
    muscu,
    'elevation_frontale',
    principaux: [epa],
    secondaires: [pec],
    materiel: {hal},
    etapes: [
      'Debout, haltères devant les cuisses.',
      "Monte les bras devant toi jusqu'à hauteur d'épaules.",
      'Redescends lentement.',
    ],
    erreurs: ['Balancer le buste.', 'Monter trop haut.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'oiseau',
    'Oiseau',
    muscu,
    'oiseau',
    principaux: [epa],
    secondaires: [dos, tra],
    materiel: {hal},
    etapes: [
      'Penché en avant, dos plat, haltères sous les épaules.',
      'Ouvre les bras sur les côtés, coudes souples.',
      'Serre les omoplates en haut, redescends.',
    ],
    erreurs: ['Se redresser.', 'Tirer avec les trapèzes.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'rowing_menton',
    'Tirage menton',
    muscu,
    'rowing_menton',
    principaux: [epa, tra],
    secondaires: [bic],
    materiel: {hal},
    poly: true,
    niveau: inter,
    etapes: [
      'Debout, haltères devant les cuisses.',
      'Monte-les le long du corps, coudes plus hauts que les mains.',
      'Arrête à hauteur de poitrine, redescends.',
    ],
    erreurs: ["Monter trop haut\u00a0: l'épaule pince.", 'Balancer.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'y_t_w',
    'Y-T-W au sol',
    pdc,
    'y_t_w',
    principaux: [epa, tra],
    secondaires: [dos, lom],
    etapes: [
      'À plat ventre, bras en Y au-dessus de la tête.',
      'Décolle les bras en serrant les omoplates, tiens deux secondes.',
      'Enchaîne en T (bras en croix) puis en W (coudes pliés).',
    ],
    erreurs: ['Décoller la tête.', 'Cambrer fort.'],
    respiration: rTirer,
  ),
  // ── Triceps ──────────────────────────────────────────────────────────────
  ExerciceSport(
    'extension_triceps',
    'Extension triceps au-dessus de la tête',
    muscu,
    'extension_triceps',
    principaux: [tri],
    materiel: {hal},
    etapes: [
      'Un haltère tenu à deux mains au-dessus de la tête.',
      'Descends-le derrière la tête, coudes pointés vers le haut.',
      'Tends les bras sans bouger les coudes.',
    ],
    erreurs: ["Coudes qui s'écartent.", 'Cambrer.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'extension_triceps_elastique',
    "Extension triceps à l'élastique",
    muscu,
    'extension_triceps_elastique',
    principaux: [tri],
    materiel: {ela},
    etapes: [
      "L'élastique sous le pied arrière, tenu derrière la tête.",
      'Tends les bras vers le plafond.',
      'Reviens lentement.',
    ],
    erreurs: ['Coudes qui bougent.', 'Cambrer.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'kickback',
    'Kickback triceps',
    muscu,
    'kickback',
    principaux: [tri],
    materiel: {hal},
    etapes: [
      'Penché en avant, coudes collés au corps, pliés à 90°.',
      "Tends les avant-bras vers l'arrière.",
      'Reviens sans bouger le haut du bras.',
    ],
    erreurs: ['Balancer le bras.', 'Coude qui descend.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'skull_crusher',
    'Barre au front aux haltères',
    muscu,
    'skull_crusher',
    principaux: [tri],
    materiel: {hal, banc},
    niveau: inter,
    etapes: [
      'Allongé, haltères au-dessus du front, bras tendus.',
      'Plie les coudes\u00a0: les haltères descendent près des tempes.',
      'Tends les bras sans écarter les coudes.',
    ],
    erreurs: ["Coudes qui s'ouvrent.", 'Bouger les épaules.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'skull_crusher_barre',
    'Barre au front',
    muscu,
    'skull_crusher_barre',
    principaux: [tri],
    materiel: {bar, banc},
    niveau: inter,
    etapes: [
      'Allongé, la barre au-dessus du front.',
      'Plie les coudes vers le front.',
      'Tends les bras.',
    ],
    erreurs: ["Coudes qui s'ouvrent.", 'Aller trop lourd.'],
    respiration: rPousser,
  ),
];
