// lib/modele/sports/catalogue/tirage.dart
//
// La banque : TIRAGE — dos, biceps, avant-bras, trapèzes (tractions,
// rowings, curls, portés).

import 'raccourcis.dart';

const List<ExerciceSport> exercicesTirage = [
  // ── Tractions et suspensions ─────────────────────────────────────────────
  ExerciceSport(
    'suspension',
    'Suspension à la barre',
    pdc,
    'suspension',
    principaux: [avb, dos],
    secondaires: [epa],
    materiel: {fixe},
    mesure: duree,
    etapes: [
      "Attrape la barre, mains à largeur d'épaules.",
      'Laisse pendre le corps, pieds décollés.',
      'Tiens en respirant, les épaules actives.',
    ],
    erreurs: ['Épaules collées aux oreilles.', 'Se balancer.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'suspension_active',
    'Suspension active',
    pdc,
    'suspension_active',
    principaux: [dos],
    secondaires: [tra, avb],
    materiel: {fixe},
    etapes: [
      'Suspendu, bras tendus.',
      'Sans plier les bras, abaisse les épaules\u00a0: le corps monte un peu.',
      'Relâche lentement.',
    ],
    erreurs: ['Plier les coudes.', 'Se balancer.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'tirage_table',
    'Tirage sous une table',
    pdc,
    'tirage_table',
    principaux: [dos],
    secondaires: [bic, epa],
    poly: true,
    etapes: [
      'Allongé sous une table très solide, agrippe le bord.',
      'Le corps droit, talons au sol.',
      'Tire la poitrine vers le bord, puis redescends.',
    ],
    erreurs: ['Table instable\u00a0: ne jamais essayer.', 'Bassin qui tombe.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'traction_australienne',
    'Traction australienne',
    pdc,
    'traction_australienne',
    principaux: [dos],
    secondaires: [bic, epa, abd],
    materiel: {fixe},
    poly: true,
    etapes: [
      'Sous une barre basse, bras tendus, corps droit.',
      'Tire la poitrine vers la barre en serrant les omoplates.',
      'Redescends lentement.',
    ],
    erreurs: ["Bassin qui s'affaisse.", 'Tirer avec le cou.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'traction_negative',
    'Traction négative',
    pdc,
    'traction_negative',
    principaux: [dos, bic],
    secondaires: [avb],
    materiel: {fixe},
    poly: true,
    niveau: inter,
    etapes: [
      'Monte menton au-dessus de la barre (saut ou chaise).',
      "Descends en cinq secondes jusqu'aux bras tendus.",
      'Remonte par un saut, recommence.',
    ],
    erreurs: ['Se laisser tomber.', 'Descendre en trois secondes.'],
    respiration: rTirer,
    intensite: 2,
  ),
  ExerciceSport(
    'traction_elastique',
    "Traction assistée à l'élastique",
    pdc,
    'traction_elastique',
    principaux: [dos, bic],
    secondaires: [avb],
    materiel: {fixe, ela},
    poly: true,
    niveau: inter,
    etapes: [
      "L'élastique noué à la barre, un pied ou un genou dedans.",
      "Tire jusqu'au menton au-dessus de la barre.",
      'Redescends bras tendus.',
    ],
    erreurs: ["Rebondir sur l'élastique.", 'Demi-amplitude.'],
    respiration: rTirer,
    intensite: 2,
  ),
  ExerciceSport(
    'traction_supination',
    'Traction en supination',
    pdc,
    'traction_supination',
    principaux: [dos, bic],
    secondaires: [avb, abd],
    materiel: {fixe},
    poly: true,
    niveau: inter,
    etapes: [
      "Mains à largeur d'épaules, paumes vers toi.",
      "Tire jusqu'au menton au-dessus de la barre.",
      "Redescends jusqu'aux bras tendus.",
    ],
    erreurs: ['Se balancer.', 'Remonter à moitié.'],
    respiration: rTirer,
    intensite: 3,
  ),
  ExerciceSport(
    'traction',
    'Tractions',
    pdc,
    'traction',
    principaux: [dos],
    secondaires: [bic, avb, abd],
    materiel: {fixe},
    poly: true,
    niveau: av,
    etapes: [
      'Mains un peu plus larges que les épaules, paumes devant.',
      'Abaisse les épaules puis tire les coudes vers les hanches.',
      'Menton au-dessus de la barre, redescends bras tendus.',
    ],
    erreurs: [
      'Élan avec les jambes.',
      'Épaules qui montent aux oreilles.',
      'Ne pas redescendre complètement.',
    ],
    respiration: rTirer,
    intensite: 3,
  ),
  ExerciceSport(
    'traction_large',
    'Tractions prise large',
    pdc,
    'traction_large',
    principaux: [dos],
    secondaires: [bic, epa],
    materiel: {fixe},
    poly: true,
    niveau: av,
    etapes: [
      'Mains nettement plus larges que les épaules.',
      'Tire la poitrine vers la barre.',
      'Redescends en contrôlant.',
    ],
    erreurs: ['Se balancer.', 'Amplitude partielle.'],
    respiration: rTirer,
    intensite: 3,
  ),
  // ── Rowings ──────────────────────────────────────────────────────────────
  ExerciceSport(
    'rowing_un_bras',
    'Rowing un bras',
    muscu,
    'rowing_un_bras',
    principaux: [dos],
    secondaires: [bic, epa],
    materiel: {hal},
    poly: true,
    parCote: true,
    etapes: [
      'Une main et un genou sur un banc ou une chaise, dos plat.',
      "L'haltère pend sous l'épaule.",
      'Tire le coude vers la hanche, puis redescends.',
    ],
    erreurs: ['Tourner le buste.', 'Tirer avec la main plutôt que le coude.'],
    respiration: rTirer,
    intensite: 2,
  ),
  ExerciceSport(
    'rowing_penche',
    'Rowing penché aux haltères',
    muscu,
    'rowing_penche',
    principaux: [dos],
    secondaires: [bic, epa, lom],
    materiel: {hal},
    poly: true,
    etapes: [
      'Penché en avant à 45°, dos plat, genoux souples.',
      'Tire les haltères vers le bas des côtes.',
      'Serre les omoplates, redescends.',
    ],
    erreurs: ['Dos rond.', 'Se redresser pour tirer.'],
    respiration: rTirer,
    intensite: 2,
  ),
  ExerciceSport(
    'rowing_penche_barre',
    'Rowing penché à la barre',
    muscu,
    'rowing_penche_barre',
    principaux: [dos],
    secondaires: [bic, lom, epa],
    materiel: {bar},
    poly: true,
    niveau: inter,
    etapes: [
      'Penché, dos plat, la barre sous les épaules.',
      'Tire la barre vers le nombril.',
      'Redescends bras tendus.',
    ],
    erreurs: ['Élan du buste.', 'Dos rond.'],
    respiration: rTirer,
    intensite: 3,
  ),
  ExerciceSport(
    'rowing_kettlebell',
    'Rowing à la kettlebell',
    muscu,
    'rowing_un_bras',
    principaux: [dos],
    secondaires: [bic],
    materiel: {kb},
    poly: true,
    parCote: true,
    etapes: [
      "Une main en appui, la kettlebell sous l'épaule.",
      'Tire le coude vers la hanche.',
      'Redescends lentement.',
    ],
    erreurs: ['Tourner le buste.', "Hausser l'épaule."],
    respiration: rTirer,
    intensite: 2,
  ),
  ExerciceSport(
    'renegade_row',
    'Rowing en planche',
    muscu,
    'renegade_row',
    principaux: [dos, abd],
    secondaires: [obl, bic, epa],
    materiel: {hal},
    poly: true,
    niveau: av,
    parCote: true,
    etapes: [
      'En planche haute, mains sur deux haltères, pieds écartés.',
      'Tire un haltère vers la hanche sans tourner le bassin.',
      'Repose-le, alterne.',
    ],
    erreurs: ['Bassin qui pivote.', 'Hanches qui montent.'],
    respiration: rTirer,
    intensite: 3,
  ),
  ExerciceSport(
    'rowing_elastique',
    "Rowing à l'élastique",
    muscu,
    'rowing_elastique',
    principaux: [dos],
    secondaires: [bic],
    materiel: {ela},
    poly: true,
    etapes: [
      "Assis, jambes tendues, l'élastique autour des pieds.",
      'Tire les mains vers le ventre, coudes serrés.',
      'Reviens lentement, le dos droit.',
    ],
    erreurs: ['Se pencher en arrière.', 'Épaules qui montent.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'tirage_elastique',
    "Tirage vertical à l'élastique",
    muscu,
    'tirage_elastique',
    principaux: [dos],
    secondaires: [bic],
    materiel: {ela},
    poly: true,
    etapes: [
      "L'élastique accroché en hauteur, bras tendus vers le haut.",
      'Tire les coudes vers les côtes.',
      'Remonte lentement.',
    ],
    erreurs: ['Cambrer.', 'Tirer avec les mains.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'face_pull',
    "Face pull à l'élastique",
    muscu,
    'face_pull',
    principaux: [epa, tra],
    secondaires: [dos],
    materiel: {ela},
    etapes: [
      "L'élastique accroché à hauteur de visage.",
      'Tire vers les yeux en écartant les mains.',
      'Coudes hauts, serre les omoplates, reviens.',
    ],
    erreurs: ['Coudes bas.', 'Se pencher en arrière.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'ecartement_elastique',
    "Écartement d'élastique",
    muscu,
    'ecartement_elastique',
    principaux: [epa, tra],
    secondaires: [dos],
    materiel: {ela},
    etapes: [
      "L'élastique tenu devant toi, bras tendus.",
      "Écarte-le jusqu'à ce qu'il touche la poitrine.",
      'Reviens lentement.',
    ],
    erreurs: ['Plier les bras.', 'Hausser les épaules.'],
    respiration: rTirer,
  ),
  // ── Dos, bas du dos ──────────────────────────────────────────────────────
  ExerciceSport(
    'superman',
    'Superman',
    pdc,
    'superman',
    principaux: [lom],
    secondaires: [fes, dos],
    etapes: [
      'À plat ventre, bras tendus devant.',
      'Décolle ensemble bras et jambes, regard vers le sol.',
      'Tiens deux secondes, redescends.',
    ],
    erreurs: ['Relever la tête.', 'Monter trop haut.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'superman_nageur',
    'Nageur',
    pdc,
    'nageur',
    principaux: [lom, dos],
    secondaires: [fes, epa],
    niveau: inter,
    etapes: [
      'À plat ventre, bras et jambes décollés.',
      'Bats bras et jambes opposés comme en nageant.',
      'Garde le regard vers le sol.',
    ],
    erreurs: ['Reposer les membres.', 'Tendre la nuque.'],
    respiration: rHiit,
  ),
  ExerciceSport(
    'extension_lombaire',
    'Extension lombaire',
    pdc,
    'extension_lombaire',
    principaux: [lom],
    secondaires: [fes],
    etapes: [
      'À plat ventre, mains aux tempes.',
      'Décolle le buste doucement.',
      'Redescends sans à-coup.',
    ],
    erreurs: ['Monter trop haut.', 'Pousser sur les mains.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'shrug',
    "Haussements d'épaules aux haltères",
    muscu,
    'shrug',
    principaux: [tra],
    secondaires: [avb],
    materiel: {hal},
    etapes: [
      'Debout, haltères le long du corps.',
      'Monte les épaules vers les oreilles.',
      'Tiens une seconde, redescends.',
    ],
    erreurs: ['Rouler les épaules.', 'Plier les bras.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'shrug_barre',
    "Haussements d'épaules à la barre",
    muscu,
    'shrug_barre',
    principaux: [tra],
    secondaires: [avb],
    materiel: {bar},
    etapes: [
      'La barre devant les cuisses.',
      'Monte les épaules droit vers le haut.',
      'Redescends lentement.',
    ],
    erreurs: ['Rouler les épaules.', 'Élan des jambes.'],
    respiration: rTirer,
  ),
  // ── Biceps et avant-bras ─────────────────────────────────────────────────
  ExerciceSport(
    'curl',
    'Curl aux haltères',
    muscu,
    'curl',
    principaux: [bic],
    secondaires: [avb],
    materiel: {hal},
    etapes: [
      'Debout, haltères le long du corps, paumes devant.',
      'Plie les coudes, qui restent collés au corps.',
      "Redescends jusqu'aux bras tendus.",
    ],
    erreurs: ['Balancer le buste.', 'Coudes qui avancent.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_marteau',
    'Curl marteau',
    muscu,
    'curl_marteau',
    principaux: [bic, avb],
    materiel: {hal},
    etapes: [
      'Haltères tenus paumes face à face.',
      'Monte-les sans tourner les poignets.',
      'Redescends lentement.',
    ],
    erreurs: ['Balancer.', "Coudes qui s'écartent."],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_zottman',
    'Curl Zottman',
    muscu,
    'curl_zottman',
    principaux: [bic, avb],
    materiel: {hal},
    niveau: inter,
    etapes: [
      'Monte en curl, paumes vers le haut.',
      'En haut, tourne les paumes vers le bas.',
      'Redescends lentement ainsi, puis retourne-les.',
    ],
    erreurs: ['Redescendre trop vite.', 'Balancer.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_barre',
    'Curl à la barre',
    muscu,
    'curl_barre',
    principaux: [bic],
    secondaires: [avb],
    materiel: {bar},
    etapes: [
      "La barre en main, paumes devant, à largeur d'épaules.",
      'Monte-la en gardant les coudes fixes.',
      'Redescends bras tendus.',
    ],
    erreurs: ['Cambrer pour monter.', 'Coudes qui avancent.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_elastique',
    "Curl à l'élastique",
    muscu,
    'curl_elastique',
    principaux: [bic],
    materiel: {ela},
    etapes: [
      "Debout sur l'élastique.",
      'Plie les coudes, qui restent contre le corps.',
      'Redescends en résistant.',
    ],
    erreurs: ['Balancer.', "Relâcher d'un coup."],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_concentre',
    'Curl concentré',
    muscu,
    'curl_concentre',
    principaux: [bic],
    materiel: {hal},
    parCote: true,
    etapes: [
      "Assis, le coude calé contre l'intérieur de la cuisse.",
      "Monte l'haltère vers l'épaule.",
      'Redescends complètement.',
    ],
    erreurs: ['Décoller le coude.', 'Aider avec le buste.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_poignet',
    'Flexion des poignets',
    muscu,
    'curl_poignet',
    principaux: [avb],
    materiel: {hal},
    etapes: [
      'Assis, avant-bras sur les cuisses, paumes vers le haut.',
      'Enroule les poignets vers le haut.',
      'Redescends lentement.',
    ],
    erreurs: ['Bouger les avant-bras.', 'Aller trop lourd.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_poignet_inverse',
    'Extension des poignets',
    muscu,
    'curl_poignet_inverse',
    principaux: [avb],
    materiel: {hal},
    etapes: [
      'Assis, avant-bras sur les cuisses, paumes vers le bas.',
      'Relève le dos des mains.',
      'Redescends lentement.',
    ],
    erreurs: ['Charge trop lourde.', 'Bouger les avant-bras.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'marche_fermier',
    'Marche du fermier',
    muscu,
    'marche_fermier',
    principaux: [avb, tra],
    secondaires: [abd, obl, mol],
    materiel: {hal},
    poly: true,
    mesure: duree,
    etapes: [
      'Un haltère lourd dans chaque main.',
      'Marche à petits pas, le buste droit, les épaules basses.',
      'Respire, ne laisse pas les haltères balancer.',
    ],
    erreurs: ["Pencher d'un côté.", "Épaules qui s'enroulent."],
    respiration: rGainage,
    intensite: 2,
  ),
  ExerciceSport(
    'marche_fermier_kb',
    'Marche du fermier à la kettlebell',
    muscu,
    'marche_fermier',
    principaux: [avb, tra],
    secondaires: [abd, obl],
    materiel: {kb},
    poly: true,
    mesure: duree,
    etapes: [
      'Une kettlebell dans chaque main.',
      'Marche droit, épaules basses.',
      'Pose-les en pliant les jambes.',
    ],
    erreurs: ['Dos rond au ramassage.', 'Pencher.'],
    respiration: rGainage,
    intensite: 2,
  ),
];
