// lib/modele/sports/catalogue/tronc.dart
//
// La banque : TRONC — gainage (planches, dead bug, hollow) et abdos
// (crunchs, relevés, rotations).

import 'raccourcis.dart';

const List<ExerciceSport> exercicesTronc = [
  // ── Planches ─────────────────────────────────────────────────────────────
  ExerciceSport(
    'planche_genoux',
    'Planche sur les genoux',
    gain,
    'planche_genoux',
    principaux: [abd],
    secondaires: [epa, lom],
    mesure: duree,
    etapes: [
      'Sur les avant-bras et les genoux, coudes sous les épaules.',
      'Aligne tête, dos et cuisses.',
      'Rentre le nombril, serre les fessiers, tiens.',
    ],
    erreurs: ["Fesses en l'air.", 'Dos creusé.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'planche',
    'Planche',
    gain,
    'planche',
    principaux: [abd],
    secondaires: [epa, lom, fes],
    mesure: duree,
    etapes: [
      'Sur les avant-bras et la pointe des pieds, coudes sous les épaules.',
      'Le corps droit de la tête aux talons.',
      'Serre les fessiers, rentre le nombril, respire.',
    ],
    erreurs: [
      "Bassin qui s'affaisse.",
      'Fesses trop hautes.',
      'Bloquer sa respiration.',
    ],
    respiration: rGainage,
  ),
  ExerciceSport(
    'planche_haute',
    'Planche bras tendus',
    gain,
    'planche_haute',
    principaux: [abd],
    secondaires: [epa, pec, tri],
    mesure: duree,
    etapes: [
      'Mains sous les épaules, bras tendus, pieds joints.',
      'Pousse le sol, le dos bien plat.',
      'Tiens en respirant.',
    ],
    erreurs: ["Épaules qui s'effondrent.", 'Bassin qui tombe.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'planche_toucher',
    "Planche toucher d'épaule",
    gain,
    'planche_toucher',
    principaux: [abd, obl],
    secondaires: [epa],
    niveau: inter,
    etapes: [
      'En planche haute, pieds écartés.',
      "Touche l'épaule opposée d'une main, sans bouger le bassin.",
      'Alterne lentement.',
    ],
    erreurs: ['Bassin qui se balance.', 'Aller trop vite.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'planche_dynamique',
    'Planche montante',
    gain,
    'planche_dynamique',
    principaux: [abd, tri],
    secondaires: [epa, pec],
    niveau: inter,
    etapes: [
      'Depuis la planche sur les avant-bras.',
      "Monte sur une main, puis l'autre, en planche haute.",
      "Redescends sur un avant-bras puis l'autre, alterne le premier.",
    ],
    erreurs: ['Bassin qui tourne.', 'Fesses qui montent.'],
    respiration: rGainage,
    intensite: 2,
  ),
  ExerciceSport(
    'planche_laterale_genoux',
    'Planche latérale sur les genoux',
    gain,
    'planche_laterale_genoux',
    principaux: [obl],
    secondaires: [abd, fes],
    mesure: duree,
    parCote: true,
    etapes: [
      "Sur le côté, en appui sur l'avant-bras et les genoux pliés.",
      'Monte le bassin\u00a0: épaules, hanches et genoux alignés.',
      'Tiens, puis change de côté.',
    ],
    erreurs: ['Bassin qui retombe.', "Épaule qui s'effondre."],
    respiration: rGainage,
  ),
  ExerciceSport(
    'planche_laterale',
    'Planche latérale',
    gain,
    'planche_laterale',
    principaux: [obl],
    secondaires: [abd, fes, epa],
    mesure: duree,
    niveau: inter,
    parCote: true,
    etapes: [
      'Sur le côté, en appui sur un avant-bras, pieds empilés.',
      'Monte les hanches, le corps en ligne droite.',
      'Tiens, puis change de côté.',
    ],
    erreurs: ['Hanches qui tombent.', 'Corps qui bascule en avant.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'planche_laterale_hanche',
    'Planche latérale, descente de hanche',
    gain,
    'planche_laterale_hanche',
    principaux: [obl],
    secondaires: [abd],
    niveau: inter,
    parCote: true,
    etapes: [
      'En planche latérale.',
      'Descends la hanche près du sol, puis remonte plus haut.',
      'Garde le rythme lent.',
    ],
    erreurs: ['Poser la hanche.', 'Tourner les épaules.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'ours_statique',
    'Ours statique',
    gain,
    'ours_statique',
    principaux: [abd, qua],
    secondaires: [epa],
    mesure: duree,
    etapes: [
      'À quatre pattes, orteils rentrés.',
      'Décolle les genoux de deux doigts.',
      'Tiens, le dos plat comme une table.',
    ],
    erreurs: ['Fesses qui montent.', 'Dos rond.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'hollow',
    'Hollow',
    gain,
    'hollow',
    principaux: [abd],
    secondaires: [obl],
    mesure: duree,
    niveau: inter,
    etapes: [
      'Sur le dos, bas du dos plaqué au sol.',
      'Décolle épaules et jambes tendues, bras au-dessus de la tête.',
      'Forme une banane, tiens.',
    ],
    erreurs: ['Bas du dos qui décolle.', 'Tirer sur la nuque.'],
    respiration: rGainage,
    intensite: 2,
  ),
  ExerciceSport(
    'dead_bug',
    'Dead bug',
    gain,
    'dead_bug',
    principaux: [abd],
    secondaires: [obl, lom],
    etapes: [
      'Sur le dos, bras vers le plafond, genoux à 90° au-dessus des hanches.',
      'Allonge un bras et la jambe opposée sans décoller le bas du dos.',
      'Reviens, alterne.',
    ],
    erreurs: ['Dos qui se cambre.', 'Aller trop vite.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'bird_dog',
    'Bird dog',
    gain,
    'bird_dog',
    principaux: [lom, abd],
    secondaires: [fes, epa],
    etapes: [
      'À quatre pattes, dos plat.',
      "Allonge un bras et la jambe opposée, à l'horizontale.",
      'Tiens deux secondes, reviens, alterne.',
    ],
    erreurs: ['Bassin qui tourne.', 'Cambrer en montant la jambe.'],
    respiration: rGainage,
  ),
  // ── Abdos ────────────────────────────────────────────────────────────────
  ExerciceSport(
    'toucher_talons',
    'Toucher de talons',
    gain,
    'toucher_talons',
    principaux: [obl],
    secondaires: [abd],
    etapes: [
      'Sur le dos, genoux pliés, épaules légèrement décollées.',
      "Glisse une main vers le talon du même côté, puis l'autre.",
      'Garde les épaules décollées tout du long.',
    ],
    erreurs: ['Reposer la tête.', 'Tirer sur la nuque.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'crunch',
    'Crunch',
    gain,
    'crunch',
    principaux: [abd],
    etapes: [
      'Sur le dos, genoux pliés, mains aux tempes.',
      'Enroule le haut du dos, les omoplates décollent.',
      'Redescends sans reposer complètement la tête.',
    ],
    erreurs: ['Tirer sur la nuque.', "Monter avec l'élan."],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'crunch_velo',
    'Crunch vélo',
    gain,
    'crunch_velo',
    principaux: [obl, abd],
    niveau: inter,
    etapes: [
      'Sur le dos, mains aux tempes, jambes décollées.',
      "Amène un coude vers le genou opposé, l'autre jambe s'allonge.",
      'Alterne lentement, comme en pédalant.',
    ],
    erreurs: ['Aller trop vite.', 'Tirer sur la tête.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'crunch_inverse',
    'Crunch inversé',
    gain,
    'crunch_inverse',
    principaux: [abd],
    etapes: [
      'Sur le dos, genoux pliés au-dessus des hanches.',
      'Enroule le bassin\u00a0: les genoux viennent vers la poitrine.',
      'Redescends lentement.',
    ],
    erreurs: ['Balancer les jambes.', 'Décoller les épaules.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'situp',
    'Relevé de buste',
    gain,
    'situp',
    principaux: [abd],
    secondaires: [obl],
    niveau: inter,
    etapes: [
      'Sur le dos, genoux pliés, pieds au sol.',
      "Enroule tout le buste jusqu'à être assis.",
      'Redescends vertèbre par vertèbre.',
    ],
    erreurs: ['Se jeter en avant.', 'Tirer sur la nuque.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'releve_jambes',
    'Relevé de jambes',
    gain,
    'releve_jambes',
    principaux: [abd],
    niveau: inter,
    etapes: [
      'Sur le dos, jambes tendues, mains sous les fesses.',
      'Monte les jambes à la verticale.',
      'Redescends sans toucher le sol, bas du dos plaqué.',
    ],
    erreurs: ['Dos qui se cambre.', 'Descendre trop vite.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'ciseaux',
    'Ciseaux',
    gain,
    'ciseaux',
    principaux: [abd],
    secondaires: [add],
    etapes: [
      'Sur le dos, jambes tendues décollées.',
      'Croise et décroise les jambes.',
      'Le bas du dos reste au sol.',
    ],
    erreurs: ['Cambrer.', 'Jambes trop basses au début.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'battements',
    'Battements de jambes',
    gain,
    'battements',
    principaux: [abd],
    etapes: [
      'Sur le dos, jambes tendues à quelques centimètres du sol.',
      'Bats-les de haut en bas, petits mouvements.',
      'Garde le bas du dos plaqué.',
    ],
    erreurs: ['Dos qui décolle.', 'Bloquer sa respiration.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'russian_twist',
    'Russian twist',
    gain,
    'russian_twist',
    principaux: [obl],
    secondaires: [abd],
    etapes: [
      'Assis, buste incliné en arrière, pieds au sol ou décollés.',
      "Tourne les épaules d'un côté puis de l'autre.",
      'Le dos reste long.',
    ],
    erreurs: ['Bouger seulement les bras.', 'Dos rond.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'russian_twist_haltere',
    "Russian twist à l'haltère",
    muscu,
    'russian_twist_haltere',
    principaux: [obl],
    secondaires: [abd],
    materiel: {hal},
    niveau: inter,
    etapes: [
      'Assis, un haltère tenu à deux mains.',
      "Pose-le d'un côté puis de l'autre de ta hanche.",
      'Garde les pieds décollés si tu peux.',
    ],
    erreurs: ['Dos rond.', 'Tourner trop vite.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'v_up',
    'V-up',
    gain,
    'v_up',
    principaux: [abd],
    secondaires: [obl],
    niveau: av,
    etapes: [
      'Allongé, bras au-dessus de la tête, jambes tendues.',
      'Monte bras et jambes ensemble\u00a0: les mains touchent les pieds.',
      'Redescends sans reposer complètement.',
    ],
    erreurs: ['Plier les jambes.', 'Se laisser tomber.'],
    respiration: rAbdos,
    intensite: 2,
  ),
  ExerciceSport(
    'woodchop',
    "Bûcheron à l'haltère",
    muscu,
    'woodchop',
    principaux: [obl],
    secondaires: [abd, epa],
    materiel: {hal},
    poly: true,
    parCote: true,
    etapes: [
      "Un haltère à deux mains au-dessus d'une épaule.",
      'Descends-le en diagonale vers la hanche opposée, en pivotant.',
      'Remonte en contrôlant.',
    ],
    erreurs: ['Dos rond.', 'Ne tourner que les bras.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'woodchop_elastique',
    "Bûcheron à l'élastique",
    muscu,
    'woodchop_elastique',
    principaux: [obl],
    secondaires: [abd],
    materiel: {ela},
    parCote: true,
    etapes: [
      "L'élastique accroché en hauteur, sur le côté.",
      'Tire en diagonale vers la hanche opposée en pivotant.',
      'Reviens lentement.',
    ],
    erreurs: ['Plier les bras.', 'Pivoter seulement les épaules.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'pallof',
    'Pallof press',
    muscu,
    'pallof',
    principaux: [obl, abd],
    materiel: {ela},
    parCote: true,
    etapes: [
      "L'élastique accroché sur le côté, à hauteur de poitrine.",
      'Pousse les mains devant toi sans laisser le buste tourner.',
      'Tiens deux secondes, ramène.',
    ],
    erreurs: ["Laisser l'élastique tourner le buste.", 'Cambrer.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'releve_genoux_suspendu',
    'Relevé de genoux suspendu',
    gain,
    'releve_genoux_suspendu',
    principaux: [abd],
    secondaires: [avb],
    materiel: {fixe},
    niveau: inter,
    etapes: [
      'Suspendu à la barre, bras tendus.',
      'Monte les genoux vers la poitrine en enroulant le bassin.',
      'Redescends sans te balancer.',
    ],
    erreurs: ['Se balancer.', 'Monter seulement les cuisses.'],
    respiration: rAbdos,
    intensite: 2,
  ),
  ExerciceSport(
    'releve_jambes_suspendu',
    'Relevé de jambes suspendu',
    gain,
    'releve_jambes_suspendu',
    principaux: [abd],
    secondaires: [avb, obl],
    materiel: {fixe},
    niveau: av,
    etapes: [
      'Suspendu, jambes tendues.',
      "Monte les jambes à l'horizontale ou plus haut.",
      'Redescends lentement.',
    ],
    erreurs: ['Élan.', 'Plier les genoux.'],
    respiration: rAbdos,
    intensite: 3,
  ),
];
