// lib/modele/sports/catalogue/variantes.dart
//
// La banque, agrandie (l'utilisateur : « agrandis mon catalogue ») : des
// VARIANTES des mouvements de base — autre matériel (kettlebell,
// élastique), autre tempo, isométrie, unilatéral.

import 'raccourcis.dart';

const List<ExerciceSport> exercicesVariantes = [
  // ── Jambes ───────────────────────────────────────────────────────────────
  ExerciceSport(
    'squat_elastique',
    "Squat à l'élastique",
    muscu,
    'squat_elastique',
    principaux: [qua, fes],
    secondaires: [isc],
    materiel: {ela},
    poly: true,
    etapes: [
      "Debout sur l'élastique, les poignées aux épaules.",
      "Descends en squat, l'élastique se détend.",
      'Remonte contre sa tension.',
    ],
    erreurs: ['Genoux qui rentrent.', 'Talons qui décollent.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'squat_sumo_kb',
    'Squat sumo à la kettlebell',
    muscu,
    'squat_sumo_charge',
    principaux: [add, fes, qua],
    materiel: {kb},
    poly: true,
    etapes: [
      'La kettlebell tenue bras tendus entre les jambes.',
      'Pieds très écartés, descends droit.',
      'Remonte en poussant les genoux dehors.',
    ],
    erreurs: ['Dos rond.', 'Genoux qui rentrent.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'squat_cosaque',
    'Squat cosaque',
    pdc,
    'squat_cosaque',
    principaux: [add, qua, fes],
    poly: true,
    niveau: av,
    parCote: true,
    etapes: [
      'Pieds très écartés.',
      "Descends tout en bas sur une jambe, l'autre tendue, pointe en "
          "l'air.",
      "Passe de l'autre côté sans te relever.",
    ],
    erreurs: ['Talon qui décolle.', 'Dos rond.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'chaise_murale_une_jambe',
    'Chaise murale sur une jambe',
    gain,
    'chaise_murale_une_jambe',
    principaux: [qua],
    secondaires: [fes],
    mesure: duree,
    niveau: av,
    parCote: true,
    etapes: [
      'En chaise murale, tends une jambe devant.',
      "Tiens sur l'autre jambe.",
      'Change de jambe.',
    ],
    erreurs: ['Genou qui rentre.', 'Remonter pour souffler.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'fente_arriere_kb',
    'Fente arrière à la kettlebell',
    muscu,
    'fente_halteres',
    principaux: [qua, fes],
    secondaires: [abd],
    materiel: {kb},
    poly: true,
    parCote: true,
    etapes: [
      'La kettlebell contre la poitrine.',
      'Grand pas en arrière, descends droit.',
      'Reviens en poussant sur le pied avant.',
    ],
    erreurs: ['Buste penché.', 'Genou qui cogne.'],
    respiration: rJambes,
    intensite: 2,
  ),
  ExerciceSport(
    'fente_pause',
    'Fente avec pause',
    pdc,
    'fente',
    principaux: [qua, fes],
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Descends en fente arrière.',
      'Tiens trois secondes, le genou à un doigt du sol.',
      "Remonte d'un coup.",
    ],
    erreurs: ['Poser le genou.', 'Buste penché.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'step_up_genou',
    'Montée avec genou levé',
    pdc,
    'step_up_genou',
    principaux: [qua, fes],
    secondaires: [abd, mol],
    materiel: {chaise},
    poly: true,
    niveau: inter,
    parCote: true,
    etapes: [
      'Monte sur la chaise sur une jambe.',
      "En haut, lève l'autre genou à hauteur de hanche.",
      'Redescends lentement.',
    ],
    erreurs: ['Élan du pied du bas.', 'Buste penché.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'pont_fessier_chaise',
    'Pont fessier pieds sur chaise',
    pdc,
    'pont_fessier_chaise',
    principaux: [fes, isc],
    materiel: {chaise},
    niveau: inter,
    etapes: [
      "Sur le dos, les talons sur l'assise d'une chaise.",
      'Monte le bassin en poussant dans les talons.',
      'Redescends lentement.',
    ],
    erreurs: ['Cambrer.', 'Chaise qui glisse.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'pont_fessier_elastique',
    "Pont fessier à l'élastique",
    pdc,
    'pont_fessier_elastique',
    principaux: [fes],
    secondaires: [add],
    materiel: {ela},
    etapes: [
      "L'élastique au-dessus des genoux.",
      "Monte le bassin en écartant les genoux contre l'élastique.",
      'Redescends sans les laisser rentrer.',
    ],
    erreurs: ['Genoux qui rentrent.', 'Cambrer.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'kickback_fessier_elastique',
    "Kickback fessier à l'élastique",
    muscu,
    'kickback_fessier_elastique',
    principaux: [fes],
    secondaires: [isc],
    materiel: {ela},
    parCote: true,
    etapes: [
      "À quatre pattes, l'élastique autour des pieds.",
      'Pousse un talon vers le plafond.',
      'Redescends en résistant.',
    ],
    erreurs: ['Cambrer.', 'Tourner le bassin.'],
    respiration: rJambes,
  ),
  ExerciceSport(
    'swing_une_main',
    'Swing à une main',
    muscu,
    'swing_une_main',
    principaux: [fes, isc],
    secondaires: [obl, avb, lom],
    materiel: {kb},
    poly: true,
    niveau: av,
    parCote: true,
    etapes: [
      'La kettlebell dans une main.',
      "Même charnière qu'un swing à deux mains.",
      'Ne laisse pas le buste tourner.',
    ],
    erreurs: ['Tirer avec le bras.', "Épaule qui s'enroule."],
    respiration: rHiit,
    intensite: 2,
  ),
  // ── Poussée ──────────────────────────────────────────────────────────────
  ExerciceSport(
    'pompe_t',
    'Pompes en T',
    pdc,
    'pompe_t',
    principaux: [pec, obl],
    secondaires: [tri, epa],
    poly: true,
    niveau: inter,
    etapes: [
      'Fais une pompe.',
      'En haut, pivote en planche latérale, un bras vers le plafond.',
      'Reviens et alterne les côtés.',
    ],
    erreurs: ['Bassin qui tombe en pivotant.', 'Pompe bâclée.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'pompe_isometrique',
    'Pompe tenue en bas',
    gain,
    'pompe_isometrique',
    principaux: [pec, tri],
    secondaires: [abd],
    mesure: duree,
    niveau: inter,
    etapes: [
      'Descends en pompe à mi-chemin du sol.',
      'Tiens la position, le corps gainé.',
      'Remonte à la fin du temps.',
    ],
    erreurs: ["Bassin qui s'affaisse.", 'Bloquer le souffle.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'pompe_hindoue',
    'Pompes hindoues',
    pdc,
    'pompe_hindoue',
    principaux: [pec, epa],
    secondaires: [tri, lom],
    poly: true,
    niveau: inter,
    etapes: [
      'Depuis le V inversé, plonge la poitrine vers le sol.',
      "Glisse vers l'avant et termine en cobra.",
      'Repousse les fesses en V inversé.',
    ],
    erreurs: ['Aller trop vite.', 'Hausser les épaules.'],
    respiration: rPousser,
    intensite: 2,
  ),
  ExerciceSport(
    'developpe_serre_barre',
    'Développé couché prise serrée',
    muscu,
    'developpe_serre_barre',
    principaux: [tri, pec],
    materiel: {bar, banc},
    poly: true,
    niveau: inter,
    etapes: [
      "Mains à largeur d'épaules sur la barre.",
      'Descends vers le bas de la poitrine, coudes serrés.',
      'Repousse en tendant les bras.',
    ],
    erreurs: [
      'Mains trop serrées\u00a0: les poignets souffrent.',
      'Coudes ouverts.',
    ],
    respiration: rPousser,
    intensite: 3,
  ),
  ExerciceSport(
    'extension_triceps_sol',
    'Extension triceps couché au sol',
    muscu,
    'extension_triceps_sol',
    principaux: [tri],
    materiel: {hal},
    etapes: [
      'Allongé au sol, haltères au-dessus du front, paumes face à face.',
      'Plie les coudes, les haltères descendent près des tempes.',
      'Tends les bras.',
    ],
    erreurs: ["Coudes qui s'ouvrent.", 'Cogner le sol.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'elevation_laterale_une',
    'Élévation latérale un bras',
    muscu,
    'elevation_laterale',
    principaux: [epa],
    materiel: {hal},
    parCote: true,
    etapes: [
      "Tiens-toi d'une main à un montant.",
      "Monte l'haltère sur le côté jusqu'à l'horizontale.",
      'Redescends lentement.',
    ],
    erreurs: ["Hausser l'épaule.", 'Balancer.'],
    respiration: rPousser,
  ),
  ExerciceSport(
    'developpe_epaules_assis',
    'Développé épaules assis',
    muscu,
    'developpe_epaules_assis',
    principaux: [epa],
    secondaires: [tri],
    materiel: {hal, chaise},
    poly: true,
    etapes: [
      'Assis, le dos droit, haltères aux épaules.',
      'Pousse au-dessus de la tête.',
      'Redescends aux épaules.',
    ],
    erreurs: ['Cambrer contre le dossier.', 'Descendre à moitié.'],
    respiration: rPousser,
    intensite: 2,
  ),
  // ── Tirage ───────────────────────────────────────────────────────────────
  ExerciceSport(
    'traction_isometrique',
    'Traction tenue en haut',
    pdc,
    'traction_isometrique',
    principaux: [dos, bic],
    secondaires: [avb],
    materiel: {fixe},
    mesure: duree,
    niveau: inter,
    etapes: [
      'Monte (ou saute) menton au-dessus de la barre.',
      'Tiens là-haut, coudes serrés.',
      'Redescends lentement à la fin.',
    ],
    erreurs: ['Menton qui glisse sous la barre.', 'Se balancer.'],
    respiration: rGainage,
    intensite: 2,
  ),
  ExerciceSport(
    'rowing_penche_supination',
    'Rowing penché en supination',
    muscu,
    'rowing_penche',
    principaux: [dos, bic],
    secondaires: [lom],
    materiel: {hal},
    poly: true,
    etapes: [
      "Penché, paumes vers l'avant.",
      'Tire les haltères vers le nombril, coudes serrés.',
      'Redescends bras tendus.',
    ],
    erreurs: ['Dos rond.', 'Élan.'],
    respiration: rTirer,
    intensite: 2,
  ),
  ExerciceSport(
    'curl_21',
    'Curl 21',
    muscu,
    'curl',
    principaux: [bic],
    materiel: {hal},
    niveau: inter,
    etapes: [
      "Sept demi-curls du bas jusqu'à l'horizontale.",
      "Sept demi-curls de l'horizontale jusqu'en haut.",
      'Sept curls complets.',
    ],
    erreurs: ['Balancer à la fin.', 'Charge trop lourde.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'curl_kettlebell',
    'Curl à la kettlebell',
    muscu,
    'curl',
    principaux: [bic],
    secondaires: [avb],
    materiel: {kb},
    etapes: [
      'La kettlebell par les cornes, bras tendus.',
      'Monte-la vers la poitrine, coudes fixes.',
      'Redescends lentement.',
    ],
    erreurs: ['Balancer.', 'Coudes qui avancent.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'shrug_kettlebell',
    "Haussements d'épaules à la kettlebell",
    muscu,
    'shrug',
    principaux: [tra],
    materiel: {kb},
    etapes: [
      'Une kettlebell dans chaque main.',
      'Monte les épaules vers les oreilles.',
      'Redescends lentement.',
    ],
    erreurs: ['Rouler les épaules.', 'Plier les bras.'],
    respiration: rTirer,
  ),
  ExerciceSport(
    'marche_valise',
    'Marche de la valise',
    muscu,
    'marche_valise',
    principaux: [obl, avb],
    secondaires: [tra, abd],
    materiel: {hal},
    mesure: duree,
    parCote: true,
    etapes: [
      "Un seul haltère lourd, d'un côté.",
      'Marche le buste parfaitement droit.',
      'Change de main à mi-temps.',
    ],
    erreurs: ["Pencher vers l'haltère.", 'Épaule qui tombe.'],
    respiration: rGainage,
  ),
  // ── Tronc ────────────────────────────────────────────────────────────────
  ExerciceSport(
    'planche_rotation',
    'Planche en T',
    gain,
    'planche_rotation',
    principaux: [obl, abd],
    secondaires: [epa],
    niveau: inter,
    etapes: [
      'En planche haute.',
      'Pivote en planche latérale, un bras vers le plafond.',
      'Reviens, change de côté.',
    ],
    erreurs: ['Bassin qui tombe.', 'Pieds qui glissent.'],
    respiration: rGainage,
  ),
  ExerciceSport(
    'hollow_rock',
    'Hollow rock',
    gain,
    'hollow_rock',
    principaux: [abd],
    secondaires: [obl],
    niveau: av,
    etapes: [
      'En position hollow, le corps en banane.',
      "Balance-toi d'avant en arrière sans casser la forme.",
      'Le bas du dos reste arrondi contre le sol.',
    ],
    erreurs: ['Plier aux hanches.', 'Relâcher la nuque.'],
    respiration: rGainage,
    intensite: 2,
  ),
  ExerciceSport(
    'crunch_oblique',
    'Crunch oblique',
    gain,
    'crunch_oblique',
    principaux: [obl],
    secondaires: [abd],
    etapes: [
      'Sur le dos, genoux pliés.',
      "Enroule en amenant l'épaule vers le genou opposé.",
      'Reviens, alterne.',
    ],
    erreurs: ['Tirer sur la nuque.', 'Élan.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'crunch_jambes_levees',
    'Crunch jambes levées',
    gain,
    'crunch_jambes_levees',
    principaux: [abd],
    niveau: inter,
    etapes: [
      'Sur le dos, jambes tendues vers le plafond.',
      'Monte les mains vers les pieds en enroulant le haut du dos.',
      'Redescends lentement.',
    ],
    erreurs: ['Balancer les jambes.', 'Tirer sur la nuque.'],
    respiration: rAbdos,
  ),
  ExerciceSport(
    'dead_bug_haltere',
    "Dead bug à l'haltère",
    gain,
    'dead_bug_haltere',
    principaux: [abd],
    secondaires: [obl],
    materiel: {hal},
    niveau: inter,
    etapes: [
      'Sur le dos, un haltère tenu bras tendus au-dessus de la poitrine.',
      'Allonge les jambes une à une sans cambrer.',
      "L'haltère ne bouge pas.",
    ],
    erreurs: ['Dos qui décolle.', 'Aller trop vite.'],
    respiration: rAbdos,
  ),
  // ── HIIT ─────────────────────────────────────────────────────────────────
  ExerciceSport(
    'squat_jack',
    'Squat jacks',
    hiit,
    'squat_jack',
    principaux: [qua, fes],
    secondaires: [add, mol],
    mesure: duree,
    niveau: inter,
    etapes: [
      'En demi-squat, mains devant la poitrine.',
      'Saute pieds écartés puis joints en restant bas.',
      'Ne te redresse pas.',
    ],
    erreurs: ['Remonter.', 'Genoux qui rentrent.'],
    respiration: rHiit,
    met: 8,
  ),
  ExerciceSport(
    'sprint_sur_place',
    'Sprint sur place',
    hiit,
    'sprint_sur_place',
    principaux: [qua, mol],
    secondaires: [abd],
    mesure: duree,
    niveau: inter,
    etapes: [
      'Cours sur place le plus vite possible.',
      'Bras très actifs.',
      "Sur l'avant des pieds.",
    ],
    erreurs: ['Genoux trop bas.', 'Se pencher en arrière.'],
    respiration: rHiit,
    met: 10,
  ),
  ExerciceSport(
    'pas_chasses',
    'Pas chassés',
    hiit,
    'pas_chasses',
    principaux: [add, qua],
    secondaires: [mol],
    mesure: duree,
    etapes: [
      'En demi-squat, fais des pas chassés rapides sur le côté.',
      "Trois pas, touche le sol, repars dans l'autre sens.",
      'Reste bas.',
    ],
    erreurs: ['Se redresser.', 'Croiser les pieds.'],
    respiration: rHiit,
    met: 7,
  ),
  ExerciceSport(
    'boxe_crochets',
    'Crochets et esquives',
    hiit,
    'boxe_crochets',
    principaux: [obl, epa],
    secondaires: [qua],
    mesure: duree,
    niveau: inter,
    etapes: [
      'En garde, enchaîne crochets gauche-droite.',
      'Plie les jambes pour esquiver sous un coup imaginaire.',
      'Reviens en garde.',
    ],
    erreurs: ['Tourner seulement les bras.', 'Garde basse.'],
    respiration: rHiit,
    met: 8,
  ),
  ExerciceSport(
    'thruster_kettlebell',
    'Squat développé à la kettlebell',
    muscu,
    'thruster',
    principaux: [qua, epa],
    secondaires: [fes, abd],
    materiel: {kb},
    poly: true,
    niveau: inter,
    etapes: [
      'La kettlebell contre la poitrine.',
      'Descends en squat.',
      'Remonte et pousse-la au-dessus de la tête.',
    ],
    erreurs: ['Cambrer.', 'Squat trop haut.'],
    respiration: rHiit,
    intensite: 2,
    met: 8,
  ),
  ExerciceSport(
    'burpee_saut_groupe',
    'Burpees sautés groupés',
    hiit,
    'burpee_saut_groupe',
    principaux: [qua, pec, fes],
    secondaires: [abd],
    poly: true,
    niveau: av,
    etapes: [
      'Un burpee complet.',
      'Finis par un saut groupé, genoux à la poitrine.',
      'Enchaîne.',
    ],
    erreurs: ['Atterrir raide.', 'Planche bâclée.'],
    respiration: rHiit,
    intensite: 3,
    met: 11,
  ),
  // ── Mobilité ─────────────────────────────────────────────────────────────
  ExerciceSport(
    'etirement_biceps',
    'Étirement des biceps',
    mobi,
    'etirement_biceps',
    principaux: [bic],
    secondaires: [pec],
    mesure: duree,
    parCote: true,
    etapes: [
      'La main contre un mur, bras tendu, pouce vers le bas.',
      "Tourne doucement le corps à l'opposé.",
      'Tiens, change de bras.',
    ],
    erreurs: ['Plier le coude.', 'Forcer.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'etirement_ischios_chaise',
    'Étirement des ischios sur chaise',
    mobi,
    'etirement_ischios_chaise',
    principaux: [isc],
    secondaires: [mol],
    materiel: {chaise},
    mesure: duree,
    parCote: true,
    etapes: [
      'Le talon sur une chaise, jambe tendue.',
      'Penche-toi depuis les hanches, le dos long.',
      'Tiens, change de jambe.',
    ],
    erreurs: ['Dos rond.', "Genou d'appui verrouillé."],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'balancier_lateral',
    'Balancier latéral',
    mobi,
    'balancier_lateral',
    principaux: [add, fes],
    mesure: duree,
    parCote: true,
    etapes: [
      'Face à un mur, les mains dessus.',
      'Balance une jambe de gauche à droite devant toi.',
      'Change de jambe.',
    ],
    erreurs: ['Tourner le bassin.', 'Forcer.'],
    respiration: rMobilite,
  ),
  ExerciceSport(
    'chien_tete_haut',
    'Chien tête en haut',
    mobi,
    'chien_tete_haut',
    principaux: [abd, pec],
    secondaires: [lom, qua],
    mesure: duree,
    niveau: inter,
    etapes: [
      'À plat ventre, mains sous les épaules.',
      'Tends les bras, les cuisses décollent du sol.',
      'Épaules basses, regard devant.',
    ],
    erreurs: ['Écraser le bas du dos.', 'Hausser les épaules.'],
    respiration: rEtirement,
  ),
  ExerciceSport(
    'torsion_assise',
    'Torsion assise',
    mobi,
    'torsion_assise',
    principaux: [obl],
    secondaires: [lom, fes],
    mesure: duree,
    parCote: true,
    etapes: [
      'Assis, un pied croisé par-dessus le genou opposé.',
      'Tourne le buste vers le genou levé, coude contre lui.',
      "Grandis-toi à l'inspiration, tourne à l'expiration.",
    ],
    erreurs: ['Dos rond.', 'Forcer avec le bras.'],
    respiration: rEtirement,
  ),
];
